### ISSUE TITLE
can not build extension

### ISSUE THREAD

**Issue by a7345678** [theia-ide/theia#6041] opened 2019-08-25 23:35 UTC
### Description
 
exection this command yo theia-extension hello-world-extension
it report:
![image](https://user-images.githubusercontent.com/4329401/63657388-dd84b700-c7d3-11e9-9248-cd1ee1c52e96.png)

hello-world-extension: npm ERR!     /Users/ruancangchao/.npm/_logs/2019-08-25T23_30_14_454Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! error Command failed with exit code 2.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 2
lerna ERR! npm ERR! hello-world-extension@0.0.0 prepare: `yarn run clean && yarn run build`
lerna ERR! npm ERR! Exit status 2
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the hello-world-extension@0.0.0 prepare script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/ruancangchao/.npm/_logs/2019-08-25T23_30_14_454Z-debug.log
lerna ERR! 
lerna ERR! 
lerna ERR! > hello-world-extension@0.0.0 prepare /Users/ruancangchao/Documents/code/theia-hello-world-extension/hello-world-extension
lerna ERR! > yarn run clean && yarn run build
lerna ERR! 
lerna ERR! yarn run v1.17.3
lerna ERR! $ rimraf lib
lerna ERR! Done in 0.20s.
lerna ERR! yarn run v1.17.3
lerna ERR! $ tsc
lerna ERR! error TS18003: No inputs were found in config file '/Users/ruancangchao/Documents/code/theia-hello-world-extension/hello-world-extension/tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["lib"]'.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/ruancangchao/Documents/code/theia-hello-world-extension/node_modules/execa/index.js:236:11)
(node:24201) UnhandledPromiseRejectionWarning: Error: Command failed: npm run prepare
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! hello-world-extension@0.0.0 prepare: `yarn run clean && yarn run build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the hello-world-extension@0.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ruancangchao/.npm/_logs/2019-08-25T23_30_14_454Z-debug.log

> hello-world-extension@0.0.0 prepare /Users/ruancangchao/Documents/code/theia-hello-world-extension/hello-world-extension
> yarn run clean && yarn run build

yarn run v1.17.3
$ rimraf lib
Done in 0.20s.
yarn run v1.17.3
$ tsc
error TS18003: No inputs were found in config file '/Users/ruancangchao/Documents/code/theia-hello-world-extension/hello-world-extension/tsconfig.json'. Specified 'include' paths were '["src"]' and 'exclude' paths were '["lib"]'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/ruancangchao/Documents/code/theia-hello-world-extension/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment] 2019-08-26 01:51
Duplicate of https://github.com/theia-ide/generator-theia-extension/issues/37
Please see the issue on the related repo for more information.

**Closed by vince-fugnitto** 2019-08-26 01:51 UTC
