### ISSUE TITLE
Cmd+Shift+P on Firefox on MacOS opens a private navigation window instead of the command palette

### ISSUE THREAD

**Issue by magopian** [theia-ide/theia#5511] opened 2019-06-18 12:36 UTC
### Description
`Cmd+Shift+P` on Firefox on MacOS opens a private navigation window instead of the command palette. This keyboard shortcut is the very first one listed on https://www.gitpod.io/docs/52_Tips_and_Tricks/

### Reproduction Steps
Focus anywhere in the editor and press `Cmd+Shift+P` while in Firefox on MacOS, and it'll open a new Firefox private navigation window.
Pressing `F1` (keyboard shortcut from the `Find Command...` in the `View` menu) works as expected (opens what i believe is the command palette)

**OS and Theia version:**

MacOS, Theia version is the one currently on https://www.gitpod.io/

**Comment by magopian** [comment] 2019-06-18 12:38
This is probably a duplicate of #1696. I guess the right fix here is to update the page on https://www.gitpod.io/docs/52_Tips_and_Tricks/#command-palette

**Comment by vince-fugnitto** [comment] 2019-06-18 12:42
Yes @magopian it is a dupp of https://github.com/theia-ide/theia/issues/1696, but it does look like gitpod lists <kbd>F1</kbd> as the first keybinding.

**Comment by magopian** [comment] 2019-06-18 12:49
As it's related to gitpod docs, I guess this should be closed here?

**Comment by benoitf** [comment] 2019-06-18 12:51
duplicate of https://github.com/theia-ide/theia/issues/1696

**Comment by vince-fugnitto** [comment] 2019-06-18 12:52
@magopian sure I'll close it for you, please feel free to open an issue in [gitpod](https://github.com/gitpod-io/gitpod/issues) if you believe the docs should be improved :)

**Comment by magopian** [comment] 2019-06-18 12:52
thanks @vince-fugnitto and @benoitf , opened in https://github.com/gitpod-io/website/issues/184

**Closed by benoitf** 2019-06-18 12:51 UTC
