### ISSUE TITLE
[terminal] Strange border in terminal with Firefox

### ISSUE THREAD

**Issue by geropl** [theia-ide/theia#3472] opened 2018-11-13 12:33 UTC
Screenshot:
<img width="937" alt="screen shot 2018-11-13 at 12 22 09" src="https://user-images.githubusercontent.com/32448529/48413596-7c11c100-e748-11e8-8b5b-d043b368f550.png">

**Comment by vince-fugnitto** [comment] 2018-11-13 15:31
I unfortunately could not reproduce it in Theia, can you verify? Perhaps it is a problem from Gitpod?

**Comment by geropl** [comment] 2018-11-15 09:37
I was able to reproduce similar border issues with pure Theia (this time the left-bottom corner) but was not fast enough for a screenshot. Since then I struggle to reproduce it in either Theia or Gitpod.

Firefox version: 63.0

**Comment by vince-fugnitto** [comment] 2018-11-15 11:29
thanks! I'll keep an eye out for it and see if I can find the reason

**Comment by svenefftinge** [comment] 2019-05-15 01:52
closing in favor of #4665

**Closed by svenefftinge** 2019-05-15 01:52 UTC
Labels: design, terminal, ui/ux
