### ISSUE TITLE
Build fails without globally installed node-gyp

### ISSUE THREAD

**Issue by jmrog** [theia-ide/theia#900] opened 2017-11-28 14:55 UTC
OS: Mac OSX Sierra
Node version: v8.8.1
Yarn version: v1.2.1

Following the [Quick Start instructions](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#quick-start), the build failed at the `yarn` command. The console output was as follows:

```
[5/5] 📃  Building fresh packages...
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
[6/7] ⠈ node-pty
[4/7] ⠈ electron
error /Users/jason/Projects/theia/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /Users/jason/Projects/theia/node_modules/node-pty
Output:
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

This seems to have failed due to the fact that node-pty uses node-gyp in its `scripts/install.js` script, and node-gyp could not be found. A workaround was to install node-gyp globally (`npm install -g node-gyp`). After that, everything worked as expected. 

I'm not sure whether this is ultimately an issue with node-pty (I was able to install node-pty itself without any issues, even when node-gyp wasn't globally installed, but I didn't investigate any further than that). Probably, the [Prerequisites section](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites) of the docs just need to be updated to specify that node-gyp is also required, at least on Mac OSX.

**Comment by akosyakov** [comment] 2017-11-28 16:31
It is strange, node-pty is explicitly added as a dependency to `@theia/process` package and should be installed in `node_modules` by calling `yarn`.

I've just explicitly uninstalled node-pty from npm and yarn global node_modules and was able to build.

**Comment by akosyakov** [comment] 2017-11-28 16:34
Please try to remove node-pty from globals, change node-pty to the latest in @theia/process package.json and run yarn again.

**Comment by svenefftinge** [comment] 2017-11-28 16:51
I cannot reproduce either. I don't have `node-gyp` installed globally either.

**Comment by jmrog** [comment] 2017-11-28 16:52
Interesting. Thanks for the quick response. I'll try uninstalling some things and seeing whether I can reproduce.

**Comment by akosyakov** [comment] 2017-11-28 16:54
What is your python version?

    python --version

**Comment by jmrog** [comment] 2017-11-28 17:03
```
> python --version
Python 2.7.10
```

**Comment by akosyakov** [comment] 2017-11-28 17:05
ok, it looks good, node-pty does not support 3.x, should be something else, your node version is higher than mine: 8.5.0

**Comment by jmrog** [comment] 2017-11-28 17:11
Uninstalled the global node-gyp, cloned the repo freshly, and tried again. Same issue reproduced:

```
[5/5] 📃  Building fresh packages...
[-/7] ⠈ waiting...
[-/7] ⠈ waiting...
[6/7] ⠈ node-pty
[4/7] ⠈ electron
error /Users/jason/theia/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /Users/jason/theia/node_modules/node-pty
Output:
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Also tried going into the `@theia/process` package.json and changing the node-pty version to "latest". Still had the same issue.

**Comment by jmrog** [comment] 2017-11-28 17:13
Ah! @akosyakov, I installed Node v8.5.0, and it worked. There must be something specific to some later node version(s).

**Comment by kittaakos** [comment] 2017-11-29 16:10
Yes, it works with `8.8.1` too.

```
$ mkdir GH-900 && cd GH-900 && node --version && npm --version && yarn --version && python --version && git clone https://github.com/theia-ide/theia \
> && cd theia \
> && yarn \
> && cd examples/browser \
> && yarn run start
v8.8.1
5.4.2
1.2.1
Python 2.7.10
Cloning into 'theia'...
remote: Counting objects: 16616, done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 16616 (delta 50), reused 67 (delta 39), pack-reused 16476
Receiving objects: 100% (16616/16616), 66.80 MiB | 2.20 MiB/s, done.
Resolving deltas: 100% (10936/10936), done.
yarn install v1.2.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning Pattern ["gulp-util@latest"] is trying to unpack in the same destination "/Users/akos.kitta/Library/Caches/Yarn/v1/npm-gulp-util-3.0.8-0054e1e744502e27c04c187c3ecc505dd54bbb4f" as pattern ["gulp-util@^3.0.0","gulp-util@^3.0.1"]. This could result in a non deterministic behavior, skipping.
warning Pattern ["request@latest"] is trying to unpack in the same destination "/Users/akos.kitta/Library/Caches/Yarn/v1/npm-request-2.82.0-2ba8a92cd7ac45660ea2b10a53ae67cd247516ea" as pattern ["request@^2.82.0","request@^2.72.0","request@2","request@^2.79.0","request@^2.45.0"]. This could result in a non deterministic behavior, skipping.
warning Pattern ["through@latest"] is trying to unpack in the same destination "/Users/akos.kitta/Library/Caches/Yarn/v1/npm-through-2.3.8-0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5" as pattern ["through@^2.3.6","through@^2.3.4","through@>=2.2.7 <3","through@2"]. This could result in a non deterministic behavior, skipping.
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
[4/5] 🔗  Linking dependencies...
warning "istanbul-instrumenter-loader@3.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0".
warning "font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[5/5] 📃  Building fresh packages...
$ yarn rebuild:clean && yarn build:clean
yarn run v1.2.1
$ rimraf .browser_modules
✨  Done in 0.17s.
yarn run v1.2.1
$ run prepare
lerna info version 2.2.0

...
// Truncated
...

lerna success - @theia/example-electron
✨  Done in 80.82s.
✨  Done in 99.22s.
yarn run v1.2.1
$ theia start
Starting server worker...

Server worker has been started. [ID: 1 | PID: 22825]
```

I am closing this. Please reopen if the problem occurs again.

**Closed by kittaakos** 2017-11-29 16:10 UTC
Labels: question

**Comment by cician** [comment] 2019-01-27 13:59
I've encountered the exact same error trying to build the electron example. For me it has something to do with the fact that I ran yarn from vscode's integrated terminal, which somehow fails to pick up $PATH from environment or ./node_modules/bin on my system. Running from a standalone terminal emulator instead works for me.
