### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by reggi** [theia-ide/theia#1813] opened 2018-04-27 23:02 UTC
Any recommendations on how to password protect the editor?

**Comment by AlexTugarev** [comment] 2018-04-28 07:36
@reggi can you explain what is meant by protection in this case?
Do you want to restrict access to the application as whole?

**Comment by reggi** [comment] 2018-04-29 00:13
Yes. The general thought is what is the recommended way to put theia on a
server and password protect the GUI so that o ly people with access can
visit.

**Comment by gorkem** [comment] 2018-04-29 13:48
duplicate of #411

**Closed** 2018-04-30 06:25 UTC
