### ISSUE TITLE
Theia breaks when opening more than one tab/window

### ISSUE THREAD

**Issue by gindik** [theia-ide/theia#1930] opened 2018-05-18 20:52 UTC
When opening two or more browser windows/tabs, Theia initially shows up fine, but as soon as the workspace root is changed in one of the instances, the other instances stop working. Specifically, the open menu becomes unresponsive, attempting to open files or expand directories fail.

Is there a way to enable Theia to support multiple browser windows?

**Comment by jopit** [comment] 2018-05-18 21:02
I'm seeing this happen even without changing the workspace root.  It was working in 0.3.8, but it's not working in 0.3.10.

**Comment by marcdumais-work** [comment] 2018-05-18 23:47
Duplicate of https://github.com/theia-ide/theia/issues/1842? You could try closing the windows/tabs, that still point to the original workspace, and check if you see the following trace in the backend: "The ws channel does not exist".

If so, we already have a fix in master, that you can try by using the published ```next``` version, on npm.

**Comment by jopit** [comment] 2018-05-19 00:27
I don't see that message when I close the tab for original workspace, but I do see it when I then try to edit a file in the tab for the second workspace.

**Comment by marcdumais-work** [comment] 2018-05-19 09:57
> I don't see that message when I close the tab for original workspace, but I do see it when I then try to edit a file in the tab for the second workspace.

Probably the same bug. Have you tried with a ```next``` version, or with a Theia built from master?

**Comment by jopit** [comment] 2018-05-22 17:17
It's working in the `next` docker image.

**Comment by marcdumais-work** [comment] 2018-05-22 19:15
@gindik I am closing this issue as a duplicate of #1842. Please re-open it if you believe this conclusion is wrong.

**Closed by marcdumais-work** 2018-05-22 19:15 UTC
