### ISSUE TITLE
Error: "shift+f7" is in collision with something else

### ISSUE THREAD

**Issue by ghatwala** [theia-ide/theia#2265] opened 2018-07-04 09:07 UTC
Theia master as of [b9941f63df57fb2876b8d74dfe4f47fcfc674048] , browser example

Environmental details
```
$ npm --version
5.6.0
$ node --version
v8.9.4
$ nodejs --version
v4.2.6
$ yarn --version
1.7.0
```
Getting below error whilst verifying the browser theia application
```
$:~/amit/theia/examples/browser$ yarn run start --hostname 0.0.0.0
yarn run v1.7.0
$ theia start --hostname 0.0.0.0
Starting server worker...
Server worker has been started. [ID: 1 | PID: 2544]
Server worker is ready to accept messages. [ID: 1 | PID: 2544]
root INFO Theia app listening on http://0.0.0.0:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 2550] Started watching: /home/test/amit/theia/examples/browser/package.json
root INFO Textmate support deactivated because WebAssembly is not detected.
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
Error: "f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
Error: "shift+f7" is in collision with something else [scope:0]

```

Any pointers to resolve the above errors ?

**Comment by AlexTugarev** [comment] 2018-07-04 09:10
duplicate of #1888 

`isInDiffEditor` context is new in monaco.

**Closed by AlexTugarev** 2018-07-04 09:10 UTC

**Comment by ghatwala** [comment] 2018-07-04 09:39
So this context needs to added to "monaco" ? 
```
- "monaco.editor.action.wordHighlight.next","f7","editorTextFocus"  <--> "monaco.editor.action.diffReview.next","f7" , "editorTextFocus"

- "monaco.editor.action.wordHighlight.prev", "shift+f7","editorTextFocus" <-->"monaco.editor.action.diffReview.prev","shift+f7","editorTextFocus"
```

**Comment by AlexTugarev** [comment] 2018-07-04 09:47
@ghatwala we register Theia commands for all of monaco's. Apparently they've introduces scopes to differentiate between code editor and diff editor, but there is not equivalent thing in Theia yet. We need to teach the keybinding service.

**Comment by ghatwala** [comment] 2018-07-04 09:50
oh thanks @AlexTugarev  for the clarification . So is there any ETA for the above changes in Theia ?
