### ISSUE TITLE
[java][TM] Error when activating opened editors 

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2324] opened 2018-07-10 08:58 UTC
I had a few editors opened in the workbench and an error occurred when I was activating them (by clicking on the tabs.)

```
errors.ts:81 Uncaught Error: Cannot read property 'isDisposed' of undefined

TypeError: Cannot read property 'isDisposed' of undefined
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.getOptionsFromEditor (text-editor-main.ts:364)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.readFromEditor (text-editor-main.ts:342)
    at TextEditorMain.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorMain.updateProperties (text-editor-main.ts:56)
    at text-editor-main.ts:94
    at Emitter.fire (event.ts:140)
    at ViewOutgoingEvents.viewEventBus.onDidScroll (codeEditorWidget.ts:433)
    at ViewOutgoingEvents.emitScrollChanged (viewOutgoingEvents.ts:45)
    at View.onScrollChanged (viewImpl.ts:333)
    at ViewEventHandler.handleEvents (viewEventHandler.ts:164)
    at ViewEventDispatcher._doConsumeQueue (viewEventDispatcher.ts:89)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.getOptionsFromEditor (text-editor-main.ts:364)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.readFromEditor (text-editor-main.ts:342)
    at TextEditorMain.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorMain.updateProperties (text-editor-main.ts:56)
    at text-editor-main.ts:94
    at Emitter.fire (event.ts:140)
    at ViewOutgoingEvents.viewEventBus.onDidScroll (codeEditorWidget.ts:433)
    at ViewOutgoingEvents.emitScrollChanged (viewOutgoingEvents.ts:45)
    at View.onScrollChanged (viewImpl.ts:333)
    at ViewEventHandler.handleEvents (viewEventHandler.ts:164)
    at ViewEventDispatcher._doConsumeQueue (viewEventDispatcher.ts:89)
    at errors.ts:81
(anonymous) @ errors.ts:81
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.ts:79
ErrorHandler.onUnexpectedError @ errors.ts:116
onUnexpectedError @ errors.ts:135
Emitter.fire @ event.ts:145
viewEventBus.onDidScroll @ codeEditorWidget.ts:433
ViewOutgoingEvents.emitScrollChanged @ viewOutgoingEvents.ts:45
View.onScrollChanged @ viewImpl.ts:333
ViewEventHandler.handleEvents @ viewEventHandler.ts:164
ViewEventDispatcher._doConsumeQueue @ viewEventDispatcher.ts:89
(anonymous) @ viewEventDispatcher.ts:72
safeInvokeNoArg @ viewImpl.ts:590
View._renderOnce @ viewImpl.ts:366
(anonymous) @ viewImpl.ts:110
ViewEventDispatcher.consumeQueue @ viewEventDispatcher.ts:68
ViewEventDispatcher.emitMany @ viewEventDispatcher.ts:63
(anonymous) @ viewImpl.ts:137
safeInvokeListener @ viewEvents.ts:395
ViewEventEmitter._emit @ viewEvents.ts:351
ViewEventEmitter._endEmit @ viewEvents.ts:343
(anonymous) @ viewModelImpl.ts:88
Emitter.fire @ event.ts:140
Scrollable._setState @ scrollable.ts:332
Scrollable.setScrollDimensions @ scrollable.ts:222
ViewLayout._updateHeight @ viewLayout.ts:117
ViewLayout.onHeightMaybeChanged @ viewLayout.ts:52
(anonymous) @ viewImpl.ts:516
safeInvokeNoArg @ viewImpl.ts:590
View._renderOnce @ viewImpl.ts:366
View.change @ viewImpl.ts:489
CodeEditorWidget.changeViewZones @ codeEditorWidget.ts:277
(anonymous) @ codelensController.ts:174
TextModel._changeDecorations @ textModel.ts:1445
TextModel.changeDecorations @ textModel.ts:1410
CommonCodeEditor.changeDecorations @ commonCodeEditor.ts:830
dispose @ codelensController.ts:173
(anonymous) @ lifecycle.ts:29
dispose @ lifecycle.ts:29
CodeLensContribution._localDispose @ codelensController.ts:78
CodeLensContribution.dispose @ codelensController.ts:64
CommonCodeEditor.dispose @ commonCodeEditor.ts:165
CodeEditorWidget.dispose @ codeEditorWidget.ts:154
StandaloneEditor.dispose @ standaloneCodeEditor.ts:329
disposable.dispose @ disposable.ts:87
../../packages/core/lib/common/disposable.js.DisposableCollection.dispose @ disposable.ts:66
push.../../packages/monaco/lib/browser/monaco-editor.js.MonacoEditor.dispose @ monaco-editor.js:250
disposable.dispose @ disposable.ts:87
../../packages/core/lib/common/disposable.js.DisposableCollection.dispose @ disposable.ts:66
../../packages/core/lib/browser/widgets/widget.js.BaseWidget.dispose @ widget.ts:49
../../packages/core/lib/browser/widgets/widget.js.BaseWidget.onCloseRequest @ widget.ts:54
../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage @ widget.js:541
invokeHandler @ index.js:433
sendMessage @ index.js:169
../../node_modules/@phosphor/widgets/lib/widget.js.Widget.close @ widget.js:378
(anonymous) @ saveable.ts:82
step @ saveable.ts:15
(anonymous) @ saveable.ts:15
fulfilled @ saveable.ts:15
Promise.then (async)
step @ saveable.ts:15
(anonymous) @ saveable.ts:15
../../packages/core/lib/browser/saveable.js.__awaiter @ saveable.ts:15
widget.close @ saveable.ts:73
../../node_modules/@phosphor/widgets/lib/dockpanel.js.DockPanel._onTabCloseRequested @ dockpanel.js:793
invokeSlot @ index.js:475
emit @ index.js:433
../../node_modules/@phosphor/signaling/lib/index.js.Signal.emit @ index.js:106
../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar._evtMouseUp @ tabbar.js:688
../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.handleEvent @ tabbar.js:451
10:56:01.908 errors.ts:81 Uncaught Error: Cannot read property 'isDisposed' of undefined

TypeError: Cannot read property 'isDisposed' of undefined
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.getOptionsFromEditor (text-editor-main.ts:364)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.readFromEditor (text-editor-main.ts:342)
    at TextEditorMain.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorMain.updateProperties (text-editor-main.ts:56)
    at text-editor-main.ts:94
    at Emitter.fire (event.ts:140)
    at ViewOutgoingEvents.viewEventBus.onDidScroll (codeEditorWidget.ts:433)
    at ViewOutgoingEvents.emitScrollChanged (viewOutgoingEvents.ts:45)
    at View.onScrollChanged (viewImpl.ts:333)
    at ViewEventHandler.handleEvents (viewEventHandler.ts:164)
    at ViewEventDispatcher._doConsumeQueue (viewEventDispatcher.ts:89)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.getOptionsFromEditor (text-editor-main.ts:364)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.readFromEditor (text-editor-main.ts:342)
    at TextEditorMain.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorMain.updateProperties (text-editor-main.ts:56)
    at text-editor-main.ts:94
    at Emitter.fire (event.ts:140)
    at ViewOutgoingEvents.viewEventBus.onDidScroll (codeEditorWidget.ts:433)
    at ViewOutgoingEvents.emitScrollChanged (viewOutgoingEvents.ts:45)
    at View.onScrollChanged (viewImpl.ts:333)
    at ViewEventHandler.handleEvents (viewEventHandler.ts:164)
    at ViewEventDispatcher._doConsumeQueue (viewEventDispatcher.ts:89)
    at errors.ts:81
(anonymous) @ errors.ts:81
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.ts:79
ErrorHandler.onUnexpectedError @ errors.ts:116
onUnexpectedError @ errors.ts:135
Emitter.fire @ event.ts:145
viewEventBus.onDidScroll @ codeEditorWidget.ts:433
ViewOutgoingEvents.emitScrollChanged @ viewOutgoingEvents.ts:45
View.onScrollChanged @ viewImpl.ts:333
ViewEventHandler.handleEvents @ viewEventHandler.ts:164
ViewEventDispatcher._doConsumeQueue @ viewEventDispatcher.ts:89
(anonymous) @ viewEventDispatcher.ts:72
safeInvokeNoArg @ viewImpl.ts:590
View._renderOnce @ viewImpl.ts:366
(anonymous) @ viewImpl.ts:110
ViewEventDispatcher.consumeQueue @ viewEventDispatcher.ts:68
ViewEventDispatcher.emitMany @ viewEventDispatcher.ts:63
(anonymous) @ viewImpl.ts:137
safeInvokeListener @ viewEvents.ts:395
ViewEventEmitter._emit @ viewEvents.ts:351
ViewEventEmitter._endEmit @ viewEvents.ts:343
(anonymous) @ viewModelImpl.ts:88
Emitter.fire @ event.ts:140
Scrollable._setState @ scrollable.ts:332
Scrollable.setScrollDimensions @ scrollable.ts:222
ViewLayout._updateHeight @ viewLayout.ts:117
ViewLayout.onHeightMaybeChanged @ viewLayout.ts:52
(anonymous) @ viewImpl.ts:516
safeInvokeNoArg @ viewImpl.ts:590
View._renderOnce @ viewImpl.ts:366
View.change @ viewImpl.ts:489
CodeEditorWidget.changeViewZones @ codeEditorWidget.ts:277
(anonymous) @ codelensController.ts:174
TextModel._changeDecorations @ textModel.ts:1445
TextModel.changeDecorations @ textModel.ts:1410
CommonCodeEditor.changeDecorations @ commonCodeEditor.ts:830
dispose @ codelensController.ts:173
(anonymous) @ lifecycle.ts:29
dispose @ lifecycle.ts:29
CodeLensContribution._localDispose @ codelensController.ts:78
CodeLensContribution.dispose @ codelensController.ts:64
CommonCodeEditor.dispose @ commonCodeEditor.ts:165
CodeEditorWidget.dispose @ codeEditorWidget.ts:154
StandaloneEditor.dispose @ standaloneCodeEditor.ts:329
disposable.dispose @ disposable.ts:87
../../packages/core/lib/common/disposable.js.DisposableCollection.dispose @ disposable.ts:66
push.../../packages/monaco/lib/browser/monaco-editor.js.MonacoEditor.dispose @ monaco-editor.js:250
disposable.dispose @ disposable.ts:87
../../packages/core/lib/common/disposable.js.DisposableCollection.dispose @ disposable.ts:66
../../packages/core/lib/browser/widgets/widget.js.BaseWidget.dispose @ widget.ts:49
../../packages/core/lib/browser/widgets/widget.js.BaseWidget.onCloseRequest @ widget.ts:54
../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage @ widget.js:541
invokeHandler @ index.js:433
sendMessage @ index.js:169
../../node_modules/@phosphor/widgets/lib/widget.js.Widget.close @ widget.js:378
(anonymous) @ saveable.ts:82
step @ saveable.ts:15
(anonymous) @ saveable.ts:15
fulfilled @ saveable.ts:15
Promise.then (async)
step @ saveable.ts:15
(anonymous) @ saveable.ts:15
../../packages/core/lib/browser/saveable.js.__awaiter @ saveable.ts:15
widget.close @ saveable.ts:73
../../node_modules/@phosphor/widgets/lib/dockpanel.js.DockPanel._onTabCloseRequested @ dockpanel.js:793
invokeSlot @ index.js:475
emit @ index.js:433
../../node_modules/@phosphor/signaling/lib/index.js.Signal.emit @ index.js:106
../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar._evtMouseUp @ tabbar.js:688
../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.handleEvent @ tabbar.js:451
```

**Comment by AlexTugarev** [comment] 2018-07-10 09:00
@kittaakos, I thinks this is a dupe of #2258

**Closed** 2018-07-10 09:03 UTC
Labels: bug, duplicate, plug-in system
