### ISSUE TITLE
[ui] [enhancement] Option to close multiple opened files

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#677] opened 2017-10-19 13:14 UTC
In THEIA, there  is no option to close the selected file (unless you use the X ), but there is no option to "remove all" files or "removes all and keep the selected one" in the THEIA editor.

**Comment by hexa00** [comment] 2017-10-19 13:50
This is a duplicate of #83

**Closed by hexa00** 2017-10-19 13:50 UTC
Labels: duplicate
