### ISSUE TITLE
Error closing a Java file

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#2382] opened 2018-07-18 15:39 UTC
Using Theia as of 4ba93d6, Electron example.

1. Start Theia in a Java project
2. Open a Java file
3. Close it

errors.ts:81 Uncaught Error: Cannot read property 'isDisposed' of undefined

TypeError: Cannot read property 'isDisposed' of undefined
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.getOptionsFromEditor (text-editor-main.ts:364)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.readFromEditor (text-editor-main.ts:342)
    at TextEditorMain.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorMain.updateProperties (text-editor-main.ts:56)
    at text-editor-main.ts:94
    at Emitter.fire (event.ts:140)
    at ViewOutgoingEvents.viewEventBus.onDidScroll (codeEditorWidget.ts:433)
    at ViewOutgoingEvents.emitScrollChanged (viewOutgoingEvents.ts:45)
    at View.onScrollChanged (viewImpl.ts:333)
    at ViewEventHandler.handleEvents (viewEventHandler.ts:164)
    at ViewEventDispatcher._doConsumeQueue (viewEventDispatcher.ts:89)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.getOptionsFromEditor (text-editor-main.ts:364)
    at Function.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorPropertiesMain.readFromEditor (text-editor-main.ts:342)
    at TextEditorMain.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorMain.updateProperties (text-editor-main.ts:56)
    at text-editor-main.ts:94
    at Emitter.fire (event.ts:140)
    at ViewOutgoingEvents.viewEventBus.onDidScroll (codeEditorWidget.ts:433)
    at ViewOutgoingEvents.emitScrollChanged (viewOutgoingEvents.ts:45)
    at View.onScrollChanged (viewImpl.ts:333)
    at ViewEventHandler.handleEvents (viewEventHandler.ts:164)
    at ViewEventDispatcher._doConsumeQueue (viewEventDispatcher.ts:89)
    at errors.ts:81
﻿

​

**Comment by AlexTugarev** [comment] 2018-07-18 15:43
closing as duplicate of #2258

**Closed by AlexTugarev** 2018-07-18 15:43 UTC
