### ISSUE TITLE
Selection menu empty after startup

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia#751] opened 2017-10-27 09:24 UTC
When you start theia in the browser and you did not open the file view then the selection menu tries to open and only shows an empty overlay which is some pixels high.
If you open the files view and select some file then the selection menu shows all entries, most of which are disabled.
If you close the file view and reload the application in the browser the selection menu is empty again.

**Comment by kittaakos** [comment] 2017-10-27 11:38
> When you start theia in the browser and you did not open the file view then the selection menu tries to open and only shows an empty overlay which is some pixels high.

Could be a Phosphor issue. I do not like it either, but this is a tiny UI glitch.

> If you open the files view and select some file then the selection menu shows all entries, most of which are disabled.

Correct, you do not have an opened editor, so you do not have active handlers for the commands. See #731.

> If you close the file view and reload the application in the browser the selection menu is empty again.

@UdoW, what would be the expected behavior? I believe this is consistent now.

**Comment by kittaakos** [comment] 2017-10-27 11:46
Possible duplicate of #731.

**Closed** 2017-10-31 07:20 UTC
