### ISSUE TITLE
An app is not responsive if select git tab without excluded node_modules

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#701] opened 2017-10-21 10:06 UTC

**Comment by kittaakos** [comment] 2017-10-22 19:12
Thanks for logging it! Did you experience this when first activating the Git widget after application startup or the performance was poor in general? This issue could be related to the Git repository discovery phase. I need to check.

**Comment by akosyakov** [comment] 2017-10-23 06:47
It was fine at the beginning but after removing node_modules from .gitignore it hangs for some time, looks like the backend is very busy.

**Comment by svenefftinge** [comment] 2017-11-25 06:44
I think this is a dupe of #758

**Closed by svenefftinge** 2017-11-25 06:44 UTC
Labels: git
