### ISSUE TITLE
[SCM] Commit message input flickers when losing/gaining the focus

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#5396] opened 2019-06-07 11:45 UTC
![screencast 2019-06-07 13-36-13](https://user-images.githubusercontent.com/1405703/59101778-5c332c00-892a-11e9-88df-2aad5ee69686.gif)

It should not.

**Comment by vince-fugnitto** [comment] 2019-06-07 11:51
duplicate of #3544?

**Closed** 2019-06-07 11:55 UTC
Labels: duplicate, scm, ui/ux
