### ISSUE TITLE
Fails to run yarn on yeoman-generator

### ISSUE THREAD

**Issue by jdhananjaya** [theia-ide/theia#382] opened 2017-08-07 14:46 UTC
I cloned a new repo, installed the pre-reqs and ran yarn.
Node version : 7.10.0
yarn version : 0.27.5
npm version : 4.2.0
nvm --version : 0.33.2

[error_log.txt](https://github.com/theia-ide/theia/files/1205145/error_log.txt)

**Comment by kittaakos** [comment] 2017-08-07 14:57
I will try it out on Ubuntu 16.04 VirtualBox image.

**Comment by kittaakos** [comment] 2017-08-07 15:36
@jdhananjaya, I was unable to reproduce your issue. It worked for me.
 - I have installed yarn from [here](https://yarnpkg.com/lang/en/docs/install/#linux-tab).
 - I have also installed Node.js 8 from [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).
 - Finally, I ran the tldr script from [here](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#tldr).

I have tried it with the following versions on Ubuntu 16.04:
```
node --version && npm --version && yarn --version
v8.2.1
5.3.0
0.27.5
```

Please, reference the full console output [here](https://github.com/theia-ide/theia/files/1205311/GH_382_kittaakos_full_console_log.txt).

**Comment by kittaakos** [comment] 2017-08-08 08:51
@jdhananjaya, based on [your comment](https://gitter.im/theia-ide/theia?at=5988d063614889d47528d06f) from Gitter; can we close this issue? Thanks!

**Comment by jdhananjaya** [comment] 2017-08-11 13:32
@kittaakos yes. This can be closed.

**Closed** 2017-08-11 13:42 UTC
