### ISSUE TITLE
Add Copy&Paste + Drag&Drop Support for External Files to Files View

### ISSUE THREAD

**Issue by cdietrich** [theia-ide/theia#566] opened 2017-09-26 06:52 UTC
it would be nice to have Copy&Paste as well as Drag&Drop Support inside the Files View. Currently there are the menu entries in electron, but nothing happens when pasting an external file copied e.g. in finder. In VSCode at least drag/drop works

**Comment by svenefftinge** [comment] 2017-09-26 07:00
duplicate of #351

**Closed by svenefftinge** 2017-09-26 07:00 UTC
