### ISSUE TITLE
[terminal] Not useable after dragging into a different tab folder

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#3838] opened 2018-12-14 12:59 UTC
It seems the terminal sometimes doesn't draw any updates after dragging into a different tab folder.

![2018-12-14 13 55 45](https://user-images.githubusercontent.com/914497/50004698-4579d100-ffa8-11e8-9024-3f71cb6b20f1.gif)

**Comment by akosyakov** [comment] 2018-12-14 13:23
@AlexTugarev after merging latest xterm?

**Comment by pdrd** [comment] 2019-02-12 10:50
We are experiencing the same behaviour. No customizations, only a package.json with several @theia-plugins all with 'latest' version and default build config. No log output. Browser is latest Google Chrome.
It's also reproducible on gitpod.io, when you drag around a terminal.

Any clues how to address this issue? It looks like a missing redraw call to the widget, because after a page reload the terminal content reappears, but my knowledge about the widget/plugin system is not sufficient to find the buggy code section.

**Comment by lmcbout** [comment] 2019-03-21 12:07
This issue still exist with Theia 0.4.0. Until I restart the client, the terminal is not usable and does not display the data already typed in the terminal.

**Comment by akosyakov** [comment] 2019-03-23 19:00
It's a bug in xterm: https://github.com/xtermjs/xterm.js/commit/69d3a4667f6d3ade4a89e71be066de0e69d82d16

It was fixed in 3.12.0. We need to upgrade xterm to pick it up.

**Closed** 2019-05-15 11:06 UTC
Labels: bug, terminal
