### ISSUE TITLE
Investigate possible automated dependency management approaches for npm

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#225] opened 2017-06-15 14:36 UTC
Such as [`npm shrinkwrap `](https://www.npmjs.com/package/npm-shrinkwrap) and/or [Greenkeeper](https://greenkeeper.io).

This task is just a placeholder, and it does not mean that we have to pick any of solutions mentioned above. Other ideas are welcome too.

**Comment by hexa00** [comment] 2017-06-15 14:40
This is a duplicate of #173 
Closing

Note @lmcgupe is taking care of this

**Closed by hexa00** 2017-06-15 14:40 UTC
