### ISSUE TITLE
Open workspace in brwoser, but no content is displayed or refreshed

### ISSUE THREAD

**Issue by VietHungPhan** [theia-ide/theia#5384] opened 2019-06-06 18:41 UTC
### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment] 2019-06-06 18:50
@VietHungPhan can you provide additional information? (ex: steps to reproduce)

**Comment by VietHungPhan** [comment] 2019-06-06 19:14
Run/start electron, then open a workspace, then watching nothing is refreshed on the display.
BR,/Hung

    On Thursday, June 6, 2019, 2:50:51 p.m. GMT-4, Vincent Fugnitto <notifications@github.com> wrote:  
 
 
@VietHungPhan can you provide additional information? (ex: steps to reproduce)

**Comment by vince-fugnitto** [comment] 2019-06-06 19:26
@VietHungPhan can you confirm if the file widget is displayed on the right?

![Screen Shot 2019-06-06 at 3 23 08 PM (1)](https://user-images.githubusercontent.com/40359487/59060547-588e9f00-886f-11e9-9169-ba0b43ff2ff7.png)


After clicking it you should should see the file tree of the workspace.

<img width="448" alt="Screen Shot 2019-06-06 at 3 23 25 PM" src="https://user-images.githubusercontent.com/40359487/59060560-62180700-886f-11e9-968d-c1e3c0507397.png">

By default, Theia does not open any widgets when its the first time opening a workspace.

**Comment by VietHungPhan** [comment] 2019-06-06 20:14
I confirm  the file widget is displayed on the righ.
BR,/Hung

    On Thursday, June 6, 2019, 3:26:30 p.m. EDT, Vincent Fugnitto <notifications@github.com> wrote:  
 
 
@VietHungPhan can you confirm if the file widget is displayed on the right?



After clicking it you should should see the file tree of the workspace.



By default, Theia does not open any widgets when its the first time opening a workspace.

**Comment by vince-fugnitto** [comment] 2019-06-07 13:26
Closing, the issue is the same as #830 and has been proposed as part of https://github.com/theia-ide/theia/pull/3942.

**Closed by vince-fugnitto** 2019-06-07 13:26 UTC
