### ISSUE TITLE
Cannot reload after updating extension

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia#693] opened 2017-10-20 13:36 UTC
I cloned the master GIT repo and followed the build instructions for the browser app. Everything worked fine. I am under Windows 10.

I loaded localhost:3000 and opened the extensions view. Then I updated the marker extension and after reloading I got an empty black screen.

See attached screen shots and log.

[updating_marker_extension.log](https://github.com/theia-ide/theia/files/1402095/updating_marker_extension.log)
![fresh_start_extensions](https://user-images.githubusercontent.com/12225215/31823395-574ea4e2-b5ac-11e7-8ff6-71f71a10ca8e.png)
![after_pressing_update_on_markers_extension](https://user-images.githubusercontent.com/12225215/31823402-5ac1dbb2-b5ac-11e7-82a4-f105afd60742.png)
![reload_message_appears](https://user-images.githubusercontent.com/12225215/31823414-63a5c2ac-b5ac-11e7-834c-135b3e5758ca.png)
![reload_pressed](https://user-images.githubusercontent.com/12225215/31823419-659aeeb6-b5ac-11e7-9a8e-10c02ea80a7f.png)

**Comment by akosyakov** [comment] 2017-10-20 13:37
@UdoW Thank you for the issue. Could you also look into the console and post errors from there, please?

**Comment by UdoW** [comment] 2017-10-20 13:42
I added the log file. Where else can I find logging output?

**Comment by akosyakov** [comment] 2017-10-20 13:46
In Chrome there is `More Tools` -> `Developer Tools` and then `Console`

**Comment by UdoW** [comment] 2017-10-20 13:49
Ok, I have to rebuild it again...

**Comment by UdoW** [comment] 2017-10-20 14:00
Chrome logs after reloading browser app:

index.js:44 Failed to start the frontend application.
module.exports.Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.catch.reason @ index.js:44
Promise rejected (async)
Object.defineProperty.value @ index.js:43
__webpack_require__ @ bootstrap 51292c9bec59add07e65:688
Object.defineProperty.value @ bootstrap 51292c9bec59add07e65:789
(anonymous) @ bootstrap 51292c9bec59add07e65:789
index.js:46 Error: Cannot apply @injectable decorator multiple times.
    at injectable.js:8
    at DecorateConstructor (Reflect.ts:1090)
    at Object.decorate (Reflect.ts:284)
    at _decorate (decorator_utils.js:42)
    at Object.decorate (decorator_utils.js:55)
    at Object.defineProperty.value (widget.ts:13)
    at __webpack_require__ (bootstrap 51292c9bec59add07e65:688)
    at fn (bootstrap 51292c9bec59add07e65:109)
    at Object.defineProperty.value (index.ts:8)
    at __webpack_require__ (bootstrap 51292c9bec59add07e65:688)

**Comment by akosyakov** [comment] 2017-10-20 14:05
@UdoW thank you

In the Theia repo using the extension manager is not going to work for everything since published extensions are outdated compared to the local.

The issue is here that we don't catch cases when frontend bindings are not compatible and because of it cannot revert installation. 

It also can be caused by https://github.com/theia-ide/theia/issues/667

**Comment by kittaakos** [comment] 2017-11-28 10:54
This issue still present if one builds an electron application with `@next` version.
```
index.js:43 Failed to start the frontend application.
module.exports.Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.catch.reason @ index.js:43
index.js:45 Error: Cannot apply @injectable decorator multiple times.
    at injectable.js:8
    at DecorateConstructor (Reflect.ts:1090)
    at Object.decorate (Reflect.ts:284)
    at _decorate (decorator_utils.js:42)
    at Object.decorate (decorator_utils.js:55)
    at Object.defineProperty.value (widget.ts:13)
    at __webpack_require__ (bootstrap 6b7c3be6c45bdb6cd747:659)
    at fn (bootstrap 6b7c3be6c45bdb6cd747:85)
    at Object.c (index.ts:8)
    at __webpack_require__ (bootstrap 6b7c3be6c45bdb6cd747:659)
module.exports.Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.catch.reason @ index.js:45
```

**Comment by vince-fugnitto** [comment] 2019-06-20 01:35
Closing since the extension manager has been deprecated #4876

**Closed by vince-fugnitto** 2019-06-20 01:35 UTC
Labels: bug, extension system
