### ISSUE TITLE
[git] the repo info in git view can't be updated when click the refresh button in some case

### ISSUE THREAD

**Issue by zixuemeng** [theia-ide/theia#3800] opened 2018-12-11 06:09 UTC
1.open a workspace which has one git repo
2.select git view tab
3.delete the repo folder in terminal
4.click the refresh button in git view
The deleted repo info is still shown in git view.

**Comment by kittaakos** [comment] 2018-12-11 11:00
Duplicate of https://github.com/theia-ide/theia/issues/927. Please reopen if required.

**Comment by zixuemeng** [comment] 2018-12-12 02:21
I don't think this issue is duplicate of #927. #927 have two git repositories, after deleting one of them, we can click the refresh button manually to update the git view. In this issue, there has only one repository, after deleting the only repository, git view can't be updated even by clicking the refresh button manually.

**Comment by zixuemeng** [comment] 2018-12-12 02:22
> Duplicate of #927. Please reopen if required.

I don't think this issue is duplicate of #927. #927 have two git repositories, after deleting one of them, we can click the refresh button manually to update the git view. In this issue, there has only one repository, after deleting the only repository, git view can't be updated even by clicking the refresh button manually.

**Comment by westbury** [comment] 2018-12-14 21:36
I was hoping this issue would be fixed by PR https://github.com/theia-ide/theia/pull/3831.  It almost is.  After deleting the repository, the repository is no longer shown in the status bar.  However I had to click away from the Git view and back before the view switched to show the orange box with "version control is not available at this time".

**Comment by zixuemeng** [comment] 2018-12-17 09:50
> I was hoping this issue would be fixed by PR #3831. It almost is. After deleting the repository, the repository is no longer shown in the status bar. However I had to click away from the Git view and back before the view switched to show the orange box with "version control is not available at this time".

As shown in the picture below,  in 'initialize' function, if there has a repo, this.toDispose.dispose will be called, so onDidChangeRepository will be disposed. In this case, git-widget will not be able to listen to the onDidChangeRepository event. In 'initialize' function, if there has no repo, 'updateView ' shall also be called to update the view.

<img width="877" alt="git-widget" src="https://user-images.githubusercontent.com/7857086/50079132-b8db4700-0223-11e9-9369-d9881c5cc828.png">

**Comment by zixuemeng** [comment] 2019-03-11 02:26
This issue still exists in version 0.4.0

**Comment by akosyakov** [comment] 2019-03-11 05:55
@zixuemeng Could you provide a PR?

**Comment by akosyakov** [comment] 2019-05-27 11:53
@vinokurig it is broken after merging SCM PR

**Closed** 2019-05-29 09:10 UTC
Labels: bug, git, scm
