### ISSUE TITLE
[websockets] Uncaught Exception:  Error: not opened

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2933] opened 2018-09-20 15:00 UTC
It does not break, but I started seeing it very often:
```
root ERROR Uncaught Exception:  Error: not opened
root ERROR Error: not opened
    at WebSocket.send (/workspace/theia/packages/core/node_modules/ws/lib/WebSocket.js:359:18)
    at WebSocketChannel.doSend (/workspace/theia/packages/core/lib/node/messaging/messaging-contribution.js:224:97)
    at WebSocketChannel.close (/workspace/theia/packages/core/lib/common/messaging/web-socket-channel.js:92:14)
    at WebSocket.<anonymous> (/workspace/theia/packages/core/lib/node/messaging/messaging-contribution.js:210:29)
    at emitTwo (events.js:131:20)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/workspace/theia/packages/core/node_modules/ws/lib/WebSocket.js:211:10)
    at _receiver.cleanup (/workspace/theia/packages/core/node_modules/ws/lib/WebSocket.js:199:39)
    at Receiver.cleanup (/workspace/theia/packages/core/node_modules/ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/workspace/theia/packages/core/node_modules/ws/lib/WebSocket.js:199:20)
```

**Comment by kittaakos** [comment] 2018-09-20 15:00
Duplicate of #2929.

**Closed** 2018-09-21 05:33 UTC
Labels: bug
