### ISSUE TITLE
Can not open files since version 0.4.0

### ISSUE THREAD

**Issue by amiga23** [theia-ide/theia#4515] opened 2019-03-09 15:51 UTC
### Description
Since version 0.4.0 I can not open any files. If I click on any file in the file tab on the left I do get the error message "TypeError: this.contextKeyService is undefined" monaco-editor-provider.js:209
Version 0.3.19 works fine.

### Reproduction Steps
docker run -d --name theia-full -it -p 3000:3000 -v /home/amiga/git:/home/project:cached theiaide/theia-full:0.4.0
Open any file either via the file menu -> "open file ..." or via the file browser on the left

**OS and Theia version:**
Theia Full 0.4.0
ArchLinux Latest
Firefox 65.0.2

**Diagnostics:** 
```
root INFO Unregistering scopes for language: java. logger-protocol.ts:112:8
root INFO The scopes have been successfully unregistered for java. logger-protocol.ts:112:8
Preference name collision detected in the schema for property: plantuml.webservice preference-contribution.ts:190:16
Preference name collision detected in the schema for property: plantuml.monochrome preference-contribution.ts:190:16
Source map error: request failed with status 404
Resource URL: http://localhost:3000/vs/loader.js
Source Map URL: ../../min-maps/vs/loader.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: http://localhost:3000/vs/editor/editor.main.js
Source Map URL: ../../../min-maps/vs/editor/editor.main.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: http://localhost:3000/vs/editor/editor.main.nls.js
Source Map URL: ../../../min-maps/vs/editor/editor.main.nls.js.map[Learn More]
root WARN e.onStart is slow, took: 337 ms logger-protocol.ts:112:8
root WARN e.onStart is slow, took: 542 ms logger-protocol.ts:112:8
root INFO Config file tasks.json does not exist under file:///home/project/osgi-scheduler-simple-quartz logger-protocol.ts:112:8
root INFO Registering scopes for language: java. logger-protocol.ts:112:8
root INFO The scopes have been successfully registered for java. logger-protocol.ts:112:8
root WARN A command java.edit.organizeImports is already registered. logger-protocol.ts:112:8
TypeError: this.contextKeyService is undefined[Learn More]
monaco-editor-provider.js:209
```

**Comment by akosyakov** [comment] 2019-03-09 18:09
@svenefftinge @marcdumais-work It would be good to fix and make 0.4.1 bugfix release from a branch.

**Comment by amiga23** [comment] 2019-03-09 19:02
Version "next" with image id 36fd112b66cf works fine. Thank you.

**Comment by marcdumais-work** [comment] 2019-03-09 21:36
Hi @akosyakov 

> It would be good to fix [...]

I think it should be fixed in master, since the `next` images work.

> [...] and make 0.4.1 bugfix release from a branch.

Ok for me. Please open an issue requesting a bugfix release and include what content you want in it (is it ok to branch-off current `master` or else from which commit, or ...). I volunteer to do the release then.

**Comment by akosyakov** [comment] 2019-03-11 10:27
hm, i cannot reproduce it with 0.4.0 branch :( something wrong with how image build, not with release

**Comment by marcdumais-work** [comment] 2019-03-11 13:23
> i cannot reproduce it with 0.4.0 branch

+1, I also can't reproduce with the main Theia repo. But I was able to reproduce when building the `full image's` (latest.package.json) Theia app outside of docker. By trial-and-error, I determined that removing `yang-theia-extension` makes the problem go away, so that would be a good place to investigate. 

Shall we transfer this issue to `https://github.com/theia-ide/yangster` ?

**Comment by akosyakov** [comment] 2019-03-11 13:30
yes, i think there or try to create an app locally in dev mode and debug why it cannot find `ContextKeyService`

**Comment by akosyakov** [comment] 2019-03-13 10:14
@marcdumais-work just had a thought, that there were breaking changes, and yang extension was updated to them, but maybe was not published as latest, only next?

**Comment by marcdumais-work** [comment] 2019-03-13 12:25
> just had a thought, that there were breaking changes, and yang extension was updated to them, but maybe was not published as latest, only next?

We had an [issue](https://github.com/theia-ide/theia-apps/issues/126) with similar symptoms in January and @JanKoehnlein [published](https://github.com/theia-ide/theia-apps/issues/126#issuecomment-458478628) a fix for both `latest` and `next` at that time. After that all worked.

### In `theia-full:latest` (has the issue):
The only thing I noticed that's strange is that two versions `sprotty` end-up being installed, with `0.4.2` being quite old: 

```
$ yarn why sprotty
yarn why v1.12.3
[1/4] Why do we have the module "sprotty"...?
[...]
=> Found "sprotty@0.4.2"
info Reasons this module exists
   - "theia-yang-extension#theia-sprotty" depends on it
   - Hoisted from "theia-yang-extension#theia-sprotty#sprotty"
[...]
=> Found "yang-sprotty#sprotty@0.6.0"
info This module exists because "theia-yang-extension#yang-sprotty" depends on it.
[...]

```
Sprotty dependency: 
`theia-sprotty` depends on `"sprotty": "^0.4.2"` and `yang-sprotty` depends on `"sprotty": "latest"` . I think yarn does not consider `0.6.0` to be compatible with `^0.4.2` and so we end-up with 2 versions of sprotty. 

Should `theia-sprotty` instead depend on `"sprotty": "latest"` or `"sprotty": "^0.6.0"` ?


### In `theia-full:next` (no issue):
`sprotty` is resolved to a single version and it works: 
```
$ yarn why sprotty
yarn why v1.12.3
[1/4] Why do we have the module "sprotty"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "sprotty@0.5.0-next.90d9d8c2"
info Reasons this module exists
   - "theia-yang-extension#yang-sprotty" depends on it
   - Hoisted from "theia-yang-extension#yang-sprotty#sprotty"
   - Hoisted from "theia-yang-extension#theia-sprotty#sprotty"
```

Both `theia-sprotty` and `yang-sprotty` depend on the same specific version: `"sprotty": "0.5.0-next.90d9d8c2"`

**Comment by JanKoehnlein** [comment] 2019-03-13 12:53
It absolutely sounds like yangster is the culprit. We haven't done a latest build for it, and it seems to run into the same old problems again. Unfortunatly, the yangster build no longer works, as all its dependencies, Theia, sprotty and theia-sprotty, have moved quite a lot.

I propose to remove YANG from this distribution until we find the time to migrate YANG to the eclipse sprotty and the latest theia, and fix its build accordingly.

**Comment by marcdumais-work** [comment] 2019-03-13 13:04
Thanks @JanKoehnlein, I will do as you suggest.

**Closed** 2019-03-13 15:32 UTC
