### ISSUE TITLE
search-in-workspace errors in windows

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#3772] opened 2018-12-06 19:32 UTC
The following error was observed on the master branch as of today, when tested in Chrome on Windows 10.

It happens every time I started theia in browser, and perform a search in search-in-workspace.

```
root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE' Error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE'
root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE' Error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE'
root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE' Error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE'
root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE' Error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE'
root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE' Error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE'
root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE' Error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE'
root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE' Error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE'
root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE' Error: UNKNOWN: unknown error, stat '\\Users\theia\Documents\theia\LICENSE'
```

**Comment by westbury** [comment] 2018-12-06 20:09
This is a duplicate of  issue https://github.com/theia-ide/theia/issues/3271.  It is fixed by PR https://github.com/theia-ide/theia/pull/3749

**Closed** 2018-12-06 20:10 UTC
Labels: OS/Windows, search in workspace
