### ISSUE TITLE
[ui] "Navigate Back" missing / not found easily

### ISSUE THREAD

**Issue by geropl** [theia-ide/theia#1320] opened 2018-02-20 13:10 UTC
As a user, when I navigate through different/ a source file, I expect to be able to navigate back. Hitting `F1` and searching for "Navigate" or "back" does not return anything, either.

**Comment by epatpol** [comment] 2018-02-20 16:23
I think this one is related or a duplicate of #73

**Comment by svenefftinge** [comment] 2018-02-21 07:52
Yes it is duplicate of #73

**Closed by svenefftinge** 2018-02-21 07:52 UTC
Labels: enhancement, help wanted, keybindings, shell
