### ISSUE TITLE
Error due to Theia trying to access non-existing folder

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#1695] opened 2018-04-13 10:25 UTC
When running Theia with yarn && cd browser-app && yarn run startTheia runs neatly, but I also get the following error in the command line:

`[2018-04-13T09:07:27.266Z] ERROR: Theia/27692 on mylaptop: Request getFileStat failed with error: Cannot find file under the given URI. URI: file:///home/myuser/Schreibtisch/TESTORDNER. [ 'Error: Cannot find file under the given URI. URI: file:///home/myuser/Schreibtisch/TESTORDNER.\n    at FileSystemNode.<anonymous> (/home/myuser/Dokumente/Recherchen/Theia/theia-extension-fenster/node_modules/@theia/filesystem/lib/node/node-filesystem.js:126:35)\n    at step (/home/myuser/Dokumente/Recherchen/Theia/theia-extension-fenster/node_modules/@theia/filesystem/lib/node/node-filesystem.js:50:23)\n    at Object.next (/home/myuser/Dokumente/Recherchen/Theia/theia-extension-fenster/node_modules/@theia/filesystem/lib/node/node-filesystem.js:31:53)\n    at fulfilled (/home/myuser/Dokumente/Recherchen/Theia/theia-extension-fenster/node_modules/@theia/filesystem/lib/node/node-filesystem.js:22:58)\n    at <anonymous>' ]`

So, the folder /home/myuser/Schreibtisch/TESTORDNER was just for test purposes and doesn't exist anymore. I though this might be a cache thing, so I ran Theia from within Chrome's Incognito Mode. Still getting the same error though.
Is this a known error? How can I solve it?

**Comment by epatpol** [comment] 2018-04-13 14:17
Can you tell us what's written under `~/.theia/recentworkspace.json` ?

Maybe the backend saved your most recent workspace, and then you deleted it, and when it reloads it opens that file and tries to reload the most recent workspace, if that's the case it is a bug. Could be something else also but let's start with checking whether or not that is the case.

**Comment by lmcbout** [comment] 2018-04-13 14:34
@epatpol Same here, I just created an empty workspace and I get the "Request getFileStat failed with error...."

**Comment by epatpol** [comment] 2018-04-13 14:36
Can you also confirm that the content of `recentworkspace.json` contains an invalid recent root (i.e deleted).

**Comment by lmcbout** [comment] 2018-04-13 14:40
Where is the file  "recentworkspace.json" located !

**Comment by jeanlucburot** [comment] 2018-04-13 14:42
`~/.theia/recentworkspace.json `

**Comment by lmcbout** [comment] 2018-04-13 14:57
In my case, there is a ssmall diff, I never created the file/folder under my workspace, (workspace/.theia/settings.json), but get the similar error reported in this issue

**Comment by epatpol** [comment] 2018-04-13 16:19
@lmcbout That's an entirely different issue

Okay so I see several problems with the current approach. First, to reproduce, just open a said workspace i.e `/tmp/test-workspace`, close the theia tab, delete the `/tmp/test-workspace` directory and reopen a theia tab. The frontend will ask the backend (which was never restarted) which root was last setup'd. Backend will answer `/tmp/test-workspace` which is fine. `WorkspaceService` then tries to check  if the root is valid by calling `getFileStat`. If it throws (undefined directory) the frontend catches the error and returns undefined but the backend throws an error because the filestat doesn't exist. I think we should simply check if the root uri exists and it does continue with the old logic.

**Comment by epatpol** [comment] 2018-04-13 17:28
I've opened a PR that should make sure we do not call `getFileStat()` on an invalid uri from the frontend.

**Comment by lmcbout** [comment] 2018-04-13 17:31
Thanks, LIke I sais also, this is a similar issue which should not occurs euither
Thanks for the explanation

**Comment by jeanlucburot** [comment] 2018-04-16 12:52
Thanks from my part as well.

**Comment by jeanlucburot** [comment] 2018-04-16 12:54
If I understand it right, this issue can be closed, right? Just asking, because the merging was blocked in issue #1700.

**Comment by epatpol** [comment] 2018-04-16 14:04
Let's just wait until the PR is officially merged, we'll close it then :)

**Comment by akosyakov** [comment] 2018-04-25 04:28
Should be fixed by https://github.com/theia-ide/theia/pull/1722

**Closed by akosyakov** 2018-04-25 04:28 UTC
