### ISSUE TITLE
Electron App doesn't work

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#79] opened 2017-05-08 08:58 UTC
When starting the electron app I get the following error dialog.
<img width="418" alt="screen shot 2017-05-08 at 10 57 27" src="https://cloud.githubusercontent.com/assets/372735/25797378/45752940-33dd-11e7-8afc-439bb70f44aa.png">

**Comment by hexa00** [comment] 2017-05-31 11:06
This is still an issue with latest master c956af8a49dc0d4cbdf9e8951b34b362d3d54863

``` electron-example@0.0.1-alpha.1 start:backend /home/hexa/ownCloud/work/theia/examples/electron
> node ./lib/backend/main.js

module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/home/hexa/ownCloud/work/theia/examples/electron/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/hexa/ownCloud/work/theia/examples/electron/node_modules/node-pty/lib/unixTerminal.js:17:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by hexa00** [comment] 2017-05-31 11:14
Also how is that passing travis CI ?

Deleting node_modules and the postinstall target in the example works as a workaround

**Comment by hexa00** [comment] 2017-05-31 17:30
In fact this is still not working because:
The backend uses nodejs 7.x with ABI 51
The frontend uses electron with ABI 53

So actually not only should we need to separate the node_modules directory from the browser and electron example but we would need to separate it from backend and frontend in the electron example...

I tried to sync the versions of node and electron's version of node but I can't since it seems there's no release of node with the ABI 53 that electron uses

**Comment by hexa00** [comment] 2017-05-31 19:48
In the end this was caused by confusion with the npm commands,

There should not be a start:backend in electron's example since the backend is started from the frontend.

I'll submit a PR to fix that confusion... 

Note however that we should decouple that, and use:
https://electron.atom.io/docs/api/environment-variables/#electron_run_as_node
See also #102

**Comment by hexa00** [comment] 2017-06-01 13:24
Fixed in #170

**Comment by kittaakos** [comment] 2017-08-16 14:15
It is broken again. Steps to reproduce:

Run the tldr electron script.
```
git clone https://github.com/theia-ide/theia \
&& cd theia \
&& yarn --unsafe-perm \
&& yarn run rebuild:electron \
&& cd examples/electron \
&& yarn run start
```

It works, then do `cd ../browser && yarn run start`. The application does not start anymore.

```
Starting express on port 'undefined'.
Allowed host is 'localhost'.
Error: The module '/Users/akos.kitta/Desktop/asd/theia/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/asd/theia/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/asd/theia/node_modules/dtrace-provider/dtrace-provider.js:42:3)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/akos.kitta/Desktop/asd/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/asd/theia/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/asd/theia/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/akos.kitta/Desktop/asd/theia/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/asd/theia/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/asd/theia/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
```

**Comment by hexa00** [comment] 2017-08-16 15:08
This is expected

You need to do: `cd ../browser && yarn rebuild:web && yarn start`

**Comment by hexa00** [comment] 2017-08-16 15:09
Since we have hoisted dependencies now with lerna we can only have 1 version of the native modules at a time so you need to rebuild when switching between the two.

**Comment by kittaakos** [comment] 2017-08-16 15:11
The example scripts seem to be inconsistent; the electron part has the rebuild step, the web one does not.

**Comment by hexa00** [comment] 2017-08-16 15:12
Right it since they are built for the web 1st it assumes it's already like that. 
Might be best to add the rebuild just in case anyway

**Comment by kittaakos** [comment] 2017-08-16 15:24
> You need to do: cd ../browser && yarn rebuild:web && yarn start

This seems to be incorrect, but still a very good hint. So I did the following:
`cd ../.. && yarn run rebuild:browser && yarn run rebuild:electron && cd examples/electron/ && yarn run start` but I can still see the error. So what should be exactly the solution?

**Comment by kittaakos** [comment] 2017-08-16 15:27
The rebuild does not seem to work, I can see something is happening when either invoking `yarn run rebuild:browser` or `yarn run rebuild:electron` but I have the same error in both cases.

**Comment by hexa00** [comment] 2017-08-16 16:27
Oops yes it's yarn run rebuild:browser , not web sorry

When you do `yarn run rebuild:browser` does it say ?:
```
native node modules are already rebuilt for browser
```
native node modules are already rebuilt for browser

**Comment by hexa00** [comment] 2017-08-16 16:28
I happened to me once that the modules were saying that but it wasn't true for some reason, I did a git clean -fdx && yarn && yarn run rebuild:whatever started to work again...

There might be an intermittent issue there...

**Comment by hexa00** [comment] 2017-08-31 18:04
Opened #445 and closing the original issue

**Closed by hexa00** 2017-08-31 18:04 UTC
Labels: bug
