### ISSUE TITLE
Editor does not automatically close when file opened in it is deleted.

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#1619] opened 2018-03-30 09:01 UTC
Tested using a custom image based from `theiaide/theia:latest`. To be tested on Theia Next image.
[URL for test instance](http://theia-gh-test-chinodesuuu-che.8a09.starter-us-east-2.openshiftapps.com/)

**steps to reproduce**:

1:) throttle your network
2:) Delete a file
3:) Notice how the tab that contains the old file doesn't close but presents a empty editor content instead.

**Comment by AlexTugarev** [comment] 2018-03-30 10:16
I think this is a duplicate of #560. Please reopen, if that’s not the case.

**Closed by AlexTugarev** 2018-03-30 10:16 UTC

**Comment by sr229** [comment] 2018-03-30 11:04
it is @AlexTugarev, thanks for informing
