### ISSUE TITLE
[Preference] Preferences file should be saved when focus is lost or toggling editor 

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2975] opened 2018-09-25 18:45 UTC
When using the preferences editor, adding a preference auto-save it. 
Note:  the **auto-save is off**.

Test1
If I edit the workspace preference directly, the auto-save does not kick-in right away.
If I  select another file from the editor list, the dirty file for the preferences remains dirty, but If I re-select again the preferences editor, then the preferences are saved and are not in a dirty state anymore.
Test2:
If I make a manual modification to the workspace preferences, then selecting the user preferences tab, the auto-save applies right away.

![preferenceautosave](https://user-images.githubusercontent.com/419051/46035361-d8ede500-c0d0-11e8-9c34-2bdb273fb98d.gif)

**Comment by marcdumais-work** [comment] 2018-09-27 14:41
It seems that the Preferences Editor saves pending changes whenever one of its tab gets back focus: 
- after switching to another editor and back to the Preferences editor
- switching between the "User Preferences" and "Workspace Preferences" sub-tabs.

Technically that's not auto-save, which saves changes after a timer expires - there is not delay here, the preferences changes are just saved immediately upon the focus changes above.

This could be by design, e.g. to avoid confusing the user by having concurrent unsaved changes when they move around between the different "preferences level" sub-tabs?

@vinokurig I think you did most of this contribution; any insights?

**Comment by vinokurig** [comment] 2018-09-28 08:55
Preferences file should be saved on toggling preference editors, but in this case preferences scope wasn't changed. I think this is a bug.

**Comment by vinokurig** [comment] 2018-09-28 09:03
So use-case 1  is bug, but use-case 2 is expected behavior.

**Comment by lmcbout** [comment] 2018-09-28 10:54
I agree with @vinokurig , I would expect the same behavior as test2 for both cases, data being saved

**Comment by marcdumais-work** [comment] 2018-09-28 13:13
Thanks @vinokurig

@lmcbout can you update the title to describe the defect more precisely (i.e. case 1 above)?

**Comment by elaihau** [comment] 2018-11-27 15:37
merged 
https://github.com/theia-ide/theia/commit/cff291acebb5d987df868127f4d49677cd41ec33

**Closed by elaihau** 2018-11-27 15:37 UTC
Labels: preferences
