### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1466] opened 2018-03-08 14:42 UTC
I pulled and ran the theiaide/theia image from Docker Hub, and left it overnight with a client connected.  Using `docker stats` to monitor the memory usage, when it started it was using 120MB, but after 18 hours of being up but doing nothing, memory was at 215MB.

**Comment by marcdumais-work** [comment] 2018-03-08 15:19
Hi John,

It's possible that it's related to #1284. In that issue, we concentrated mostly on the spectacular virtual memory leak, but there was also an apparent but more modest increase in the resident memory used (that one seemed to stop growing after a few hundred megs). 

If you still have your instance running, you might look at the virtual memory being used. 

Another potential thing to try is to "stimulate" file watchers by quickly changing a file, within your workspace, and see if the memory seems to leak faster. e.g. run something like:

```
#!/bin/bash
counter=1
while [ $counter -le 2 ]
do
	echo "a" >> /tmp/file.txt
        sleep 0.01
done
```

Where you change ```/tmp/file.txt``` to point to a file within your workspace

Without such stimulation, there could still be a slower leak, when some Theia extensions trigger file WATCHER. e.g. the git extension seems to do so once every few seconds.

**Comment by jopit** [comment] 2018-03-08 19:24
It does look like it's leaking virtual memory:

```
Thu Mar  8 11:30:08 EST 2018
root     18942  0.1  0.7 123188992 128040 ?    Sl   Mar07   1:27 /usr/local/bin/node /home/theia/node_modules/@theia/core/lib/node/messaging/ipc-bootstrap.js

Thu Mar  8 14:09:25 EST 2018
root     18942  0.1  0.7 140137944 131160 ?    Sl   Mar07   1:38 /usr/local/bin/node /home/theia/node_modules/@theia/core/lib/node/messaging/ipc-bootstrap.js
```

**Comment by marcdumais-work** [comment] 2018-03-08 19:35
Another symptom of this leak is that it clears when the front-end is reloaded. 

If that happens too in your case, then this is probably a duplicate of #1284. I think it would be interesting for you to add to that issue, what you reported above, since I think we have not yet documented the leak in resident memory. 

We have insulated the problem to the file watcher library we use, called "nsfw", and reported the issue on their GH: https://github.com/Axosoft/nsfw/issues/48 , but had no time yet to dig deeper or try to fix it ourselves.

**Comment by jopit** [comment] 2018-03-08 19:44
Yes, reloading the front end frees up both the virtual and resident memory

```
Thu Mar  8 14:40:30 EST 2018
root     31035  4.3  0.2 671096 39492 ?        Sl   14:40   0:00 /usr/local/bin/node /home/theia/node_modules/@theia/core/lib/node/messaging/ipc-bootstrap.js
```

**Comment by marcdumais-work** [comment] 2018-03-08 19:50
closing as duplicate of #1284

**Closed by marcdumais-work** 2018-03-08 19:50 UTC
