### ISSUE TITLE
[Windows] Cannot open browser app

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia#837] opened 2017-11-15 13:47 UTC
When I start the browser app with http://localhost:3000 I get following error in the browser console:
(the browser window is black and shows my a waiting cursor - rotating points)

Uncaught TypeError: setImmediate is not a function
    at triggerMessageQueue (main.js:231)
    at StreamMessageReader.callback (main.js:280)
    at StreamMessageReader.onData (messageReader.js:211)
    at ReadableStream.<anonymous> (messageReader.js:176)
    at ReadableStream.EventEmitter.emit (events.js:81)
    at ReadableStream.Readable.read (_stream_readable.js:462)
    at flow (_stream_readable.js:806)
    at emitReadable_ (_stream_readable.js:498)
    at afterTickOne (index.js:23)
    at Item.run (browser.js:153)

I get this in Chrome and Firefox. 

My versions:
node: 8.9.0
yarn: 1.3.2
npm: 5.5.1

Git commit was: commit 2c8b92f1743a54049380aafa77b220c17b2d9215

**Comment by kittaakos** [comment] 2017-11-15 13:51
@UdoW, I would say you have a stale process running. You are on Windows, right? Could you please check the open ports and verify my assumption with `netstat -o -a`? If that is the case, please terminate the stale process, and check the browser again.

Meanwhile, I try to collect the corresponding issues and thread from Gitter.

**Comment by kittaakos** [comment] 2017-11-15 13:57
I did not find the Gitter entry. Just [this](https://gitter.im/theia-ide/theia?at=59ca8d39210ac2692074a2f1), but that is related to the WDIO.

**Comment by UdoW** [comment] 2017-11-15 16:44
I do not have any node process running and it still does not work.

**Comment by kittaakos** [comment] 2017-11-15 16:47
Thanks for the feedback, I try to reproduce it right now.

> Git commit was: commit 2c8b92f

As I see, you are have tried it on the HEAD of the master branch. I get back to you in 5 minutes or so...

**Comment by kittaakos** [comment] 2017-11-15 17:01
I can confirm, it works. See attached [full console log](https://github.com/theia-ide/theia/files/1475608/GH-837-full-console-log.txt).

**Comment by kittaakos** [comment] 2017-11-15 17:02
I have tried it with Chrom, but I'll give it a try with another browser.

**Comment by kittaakos** [comment] 2017-11-15 17:02
Meanwhile, you could perhaps attach your full console log to this issue too, so that we can investigate the problem.

**Comment by kittaakos** [comment] 2017-11-15 17:04
It works from Edge too.

**Comment by UdoW** [comment] 2017-11-15 17:13
Ok, I will try it again with a console log.

**Comment by hexa00** [comment] 2017-11-16 01:02
One thing to try too is with a browser window in private mode ?

It's possible the workspace restore is having issues.  With a private mode tab if the issue is not there it is most likely the restore.

**Comment by UdoW** [comment] 2017-11-17 12:10
I tried with private mode but still the same error.

**Comment by UdoW** [comment] 2017-11-17 12:14
I tried again with commit 2ceb174b37d13a29cb0536441a99403d266dcdf8 and logged all output.
[yarn_log.txt](https://github.com/theia-ide/theia/files/1482216/yarn_log.txt)
[browser_yarn_log.txt](https://github.com/theia-ide/theia/files/1482218/browser_yarn_log.txt)

And still the same error in the browser log:
Failed to load resource: the server responded with a status of 404 (Not Found)
9main.js:231 Uncaught TypeError: setImmediate is not a function
    at triggerMessageQueue (main.js:231)
    at StreamMessageReader.callback (main.js:280)
    at StreamMessageReader.onData (messageReader.js:211)
    at ReadableStream.<anonymous> (messageReader.js:176)
    at ReadableStream.EventEmitter.emit (events.js:81)
    at ReadableStream.Readable.read (_stream_readable.js:462)
    at flow (_stream_readable.js:806)
    at emitReadable_ (_stream_readable.js:498)
    at afterTickOne (index.js:23)
    at Item.run (browser.js:153)

**Comment by hexa00** [comment] 2017-11-17 12:22
I see this:
```
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\readable-stream\lib\_stream_duplex.js -> ..\..\node_modules\readable-stream\lib\_stream_readable.js -> ..\..\node_modules\readable-stream\lib\_stream_duplex.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\readable-stream\lib\_stream_writable.js -> ..\..\node_modules\readable-stream\lib\_stream_duplex.js -> ..\..\node_modules\readable-stream\lib\_stream_writable.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\inversify\lib\syntax\binding_on_syntax.js -> ..\..\node_modules\inversify\lib\syntax\binding_when_syntax.js -> ..\..\node_modules\inversify\lib\syntax\binding_on_syntax.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\inversify\lib\syntax\binding_when_syntax.js -> ..\..\node_modules\inversify\lib\syntax\binding_on_syntax.js -> ..\..\node_modules\inversify\lib\syntax\binding_when_syntax.js
@theia/example-browser: WARNING in Circular dependency detected:
@theia/example-browser: ..\..\node_modules\readable-stream\lib\_stream_readable.js -> ..\..\node_modules\readable-stream\lib\_stream_duplex.js -> ..\..\node_modules\readable-stream\lib\_stream_readable.js
lerna success run Ran npm script 'prepare' in packages:
```

Is that familiar to anyone ?

**Comment by kittaakos** [comment] 2017-11-17 12:27
Yes, it was always the case on Windows. See: https://github.com/theia-ide/theia/blob/c696ba2a99d643eba54052ba47880298224be67d/dev-packages/application-package/src/generator/webpack-generator.ts#L146

**Comment by hexa00** [comment] 2017-11-17 13:31
OK hard to tell what is going on :(

Actually since this is a 404 @UdoW could you check the Network tab in the inspector and check what resource it's trying to fetch ?

**Comment by UdoW** [comment] 2017-11-17 14:02
![network](https://user-images.githubusercontent.com/12225215/32950907-58369088-cba8-11e7-87a4-2dc53ae4df1f.png)

**Comment by UdoW** [comment] 2017-11-17 14:57
This ist what I see in the browser:
![browser](https://user-images.githubusercontent.com/12225215/32953293-0a80f222-cbb0-11e7-9329-6f6d7b89c927.png)

**Comment by hexa00** [comment] 2017-11-17 15:06
:( I don't see the 404 in the network window... is there one ?

**Comment by svenefftinge** [comment] 2017-11-17 16:04
Maybe this is related https://www.bountysource.com/issues/44341029-multiple-modules-with-names-that-only-differ-in-casing-setimmediate

**Comment by UdoW** [comment] 2017-11-20 08:36
Hi Sven, probably this is the bug. I also have a file system here on Windows which ignores the case of fileames. 
In the referenced bug report for webpack they mentioned that you should not use "." in the modules list. Does Theia use "." in the modules list?

**Comment by svenefftinge** [comment] 2017-11-20 14:37
Do you have a reference? I am not sure what you are referring to.

**Comment by UdoW** [comment] 2017-11-21 07:24
This is the reference: https://github.com/webpack/webpack/issues/4876

**Comment by akosyakov** [comment] 2017-11-21 07:32
interesting that the difference is not in node_modules, but in the project location, i.e. !D:\Projekte vs !D:\projekte

**Comment by akosyakov** [comment] 2017-11-21 07:41
@UdoW could you do cd with the lower case path before running webpack?

**Comment by akosyakov** [comment] 2017-11-21 07:45
this issue seems to be similar to ours: https://github.com/gdi2290/angular-starter/issues/926
if the difference would be in js files then it would mean that we use upper-case imports somewhere, otherwise, it does not look like we can do something about it.

**Comment by kittaakos** [comment] 2017-11-27 13:08
I give it another try. I hope I can reproduce the defect. That is my plan:
 - I use a fresh clone.
 - I use `cmd.exe`. (If it does not fail, I'll try it with PS too. It works from GitBash.)
 - I intentionally mess up the case sensitivity in the path.

**Comment by kittaakos** [comment] 2017-11-27 14:48
Worked fine both from `cmd.exe` and `PS`. @UdoW, are you using a mapped network drive? Please do the following: execute the single-line command and share the console output with us again. Instead of piping the output into files, just copy and paste the entire output into a text file and attach it to this issue. Thank you!

```
mkdir tmp && cd tmp && git clone https://github.com/theia-ide/theia.git && cd theia && node --version && npm --version && yarn --version && python --version && yarn && cd examples/browser && yarn run start
```

Furthermore, could you please try to use only lower-case characters in your path? It is indeed not a possible fix, I am just still trying to narrow the cause of the issue.

**Comment by kittaakos** [comment] 2018-01-22 10:07
@UdoW, are there any updates on this thread?

**Comment by kittaakos** [comment] 2018-01-24 07:35
I am closing this. Please reopen, or create a follow up if the problem still present.

**Closed by kittaakos** 2018-01-24 07:35 UTC
Labels: OS/Windows
