### ISSUE TITLE
Preferences preview editor without vertical scroll bar.

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [theia-ide/theia#4837] opened 2019-04-08 10:04 UTC
### Description
Preferences editor without vertical scroll bar. 

### Reproduction Steps
1. Open: File -> Settings -> Open Preferences
2. Open some preferences with long definition and make preferences editor shorter.
Actual result: preferences editor display content without vertical scrollbar.
Expected result: preferences editor should have vertical scrollbar.

**OS and Theia version:**
Kubuntu 18.04, Theia 0.5.0 and current master branch.

**Comment by yeweiasia** [comment] 2019-04-10 03:19
this may caused by the tree widget, the file-tree widget has the same problem.

**Comment by akosyakov** [comment] 2019-04-10 04:37
@yeweiasia something else you would like to have a look at? :D

**Comment by yeweiasia** [comment] 2019-04-10 06:07
@akosyakov yeah, do you have someting to recommand?

**Comment by akosyakov** [comment] 2019-04-10 06:42
@yeweiasia checking again, it's actually by design that vertical scrollbar is missing in the explorer. 

I'm not sure that it is something worth looking into. We have plans completely rewrite the preference widget.

**Comment by vince-fugnitto** [comment] 2019-07-03 19:39
@AndrienkoAleksandr it is by design that most trees do not have the vertical scrollbar and that their values are visible when hovering with the use of tooltips. I'll close the issue for now.

The same is true for the `explorer`, `outline`, `search-in-workspace` widgets among others.

**Closed by vince-fugnitto** 2019-07-03 19:39 UTC
Labels: bug, help wanted, preferences
