### ISSUE TITLE
Command Palette isn't opened after closing a workspace

### ISSUE THREAD

**Issue by azatsarynnyy** [theia-ide/theia#5887] opened 2019-08-08 08:30 UTC
### Description
 
Nothing happens when I'm trying to open Command Palette in Theia with no workspace is opened.

### Reproduction Steps

Make sure no workspace is opened and press `F1` to open Command Palette.

**OS and Theia version:**
Theia 0.9.0
Commit id 0953ba77fe0b9c90bd7c122355acedc177ea5d0b

**Diagnostics:** 

In browser's dev console:
```
Uncaught (in promise) TypeError: Cannot read property 'uri' of undefined
    at CppBuildConfigurationManagerImpl.push.../../packages/cpp/lib/browser/cpp-build-configurations.js.CppBuildConfigurationManagerImpl.getActiveConfig (cpp-build-configurations.ts:274)
    at Object.isVisible (cpp-build-configurations-ui.ts:211)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.getVisibleHandler (command.ts:300)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.isVisible (command.ts:255)
    at quick-command-service.ts:163
    at Array.filter (<anonymous>)
    at QuickCommandService.../../packages/core/lib/browser/quick-open/quick-command-service.js.QuickCommandService.normalize (quick-command-service.ts:163)
    at QuickCommandService.../../packages/core/lib/browser/quick-open/quick-command-service.js.QuickCommandService.getCommands (quick-command-service.ts:149)
    at QuickCommandService.../../packages/core/lib/browser/quick-open/quick-command-service.js.QuickCommandService.init (quick-command-service.ts:64)
    at PrefixQuickOpenService.<anonymous> (prefix-quick-open-service.ts:178)
```

**Comment by akosyakov** [comment] 2019-08-08 08:34
@azatsarynnyy I've just tried on master and `F1` works for me. Do you have anything special on your setup?

**Comment by akosyakov** [comment] 2019-08-08 08:35
We've merged enhancements to the quick palette yesterday: https://github.com/theia-ide/theia/commit/d47d42ee069f33abcd6383f566e6cab1e48cd503 Could you try before this commit?

If it is reproducible, then it is critical regression and has to be tackled today/tomorrow or reverted.

**Comment by azatsarynnyy** [comment] 2019-08-08 09:07
@akosyakov I've built Theia from the commit 62fe752218b0ad2b334454286313cb47d737c61f and everything works well.
So, most likely the problem has appeared after the https://github.com/theia-ide/theia/pull/4603

**Comment by azatsarynnyy** [comment] 2019-08-08 09:22
@akosyakov it's weird that it works well on your side. I've also tried in Chrome incognito mode and in FF - the same error.

**Comment by RomanNikitenko** [comment] 2019-08-08 09:26
I can reproduce the issue when I don't have opened project
![bug_f1](https://user-images.githubusercontent.com/5676062/62691600-af336900-b9d7-11e9-8f5c-ce271918ed87.png)

**Comment by azatsarynnyy** [comment] 2019-08-08 09:29
yep, it's reproducible with closed workspace only. Thanks, @RomanNikitenko for checking this out!

**Comment by azatsarynnyy** [comment] 2019-08-08 09:31
BTW after closing a workspace, one more error is reported
```
logger-protocol.ts:112 root ERROR TypeError: Cannot read property 'className' of undefined
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderOptionElement (http://localhost:3000/88.bundle.js:2475:61)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderOptionContainer (http://localhost:3000/88.bundle.js:2463:36)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchField (http://localhost:3000/88.bundle.js:2428:36)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchAndReplace (http://localhost:3000/88.bundle.js:2377:32)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchHeader (http://localhost:3000/88.bundle.js:2369:46)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.onUpdateRequest (http://localhost:3000/88.bundle.js:2339:22)
    at SearchInWorkspaceWidget.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (http://localhost:3000/bundle.js:23628:22)
    at invokeHandler (http://localhost:3000/bundle.js:7614:21)
    at sendMessage (http://localhost:3000/bundle.js:7350:13)
    at runMessageLoop (http://localhost:3000/bundle.js:7664:17)
```

**Comment by azatsarynnyy** [comment] 2019-08-08 09:34
the title/description has been updated with the details

**Comment by azatsarynnyy** [comment] 2019-08-08 11:17
FYI, I filed the issue https://github.com/theia-ide/theia/issues/5889 related to another error reported on closing a workspace.

**Closed** 2019-08-08 14:24 UTC
Labels: bug, shell

**Comment by marechal-p** [comment] 2019-08-08 15:08
@akosyakov should we catch errors when executing contribution code?

This issue seems to have happened because somehow the `isVisible` method was throwing and stopped the whole contribution iteration.
