### ISSUE TITLE
Window is not defined error when starting theia backend

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#1161] opened 2018-01-29 15:40 UTC
I've traced this to setRootLogger:
  
```
ReferenceError: window is not defined
    at Object.setRootLogger (/home/eantotr/sync/work/theia/packages/core/lib/common/logger.js:55:29)
    at Object.initialize (/home/eantotr/sync/work/theia/packages/core/lib/node/logger-backend-module.js:45:26)
    at new BackendApplication (/home/eantotr/sync/work/theia/packages/core/lib/node/backend-application.js:151:38)
    at _createInstance (/home/eantotr/sync/work/theia/node_modules/inversify/lib/resolution/instantiation.js:21:12)
    at Object.resolveInstance (/home/eantotr/sync/work/theia/node_modules/inversify/lib/resolution/instantiation.js:41:18)
    at /home/eantotr/sync/work/theia/node_modules/inversify/lib/resolution/resolver.js:72:42
    at Object.resolve (/home/eantotr/sync/work/theia/node_modules/inversify/lib/resolution/resolver.js:96:12)
    at /home/eantotr/sync/work/theia/node_modules/inversify/lib/container/container.js:245:37
    at Container._get (/home/eantotr/sync/work/theia/node_modules/inversify/lib/container/container.js:236:44)
    at Container.get (/home/eantotr/sync/work/theia/node_modules/inversify/lib/container/container.js:195:21)

```

@akosyakov could you take a look ?

**Comment by kittaakos** [comment] 2018-01-30 08:07
We could change the ‘!!window’ with a ‘typeof window !== 'undefined'’ check. That should fix the problem

**Comment by akosyakov** [comment] 2018-01-30 08:14
What is the problem with `!!window`?

**Comment by akosyakov** [comment] 2018-01-30 08:21
We can replace if it fixes the issue. I just don't understand what is the issue.

**Comment by kittaakos** [comment] 2018-01-30 08:38
I agree with you but it seems, there is a difference when something is just undefined or an unknown variable. See point #2 here: http://2ality.com/2013/04/check-undefined.html

**Comment by akosyakov** [comment] 2018-01-30 08:45
ok, makes sense, js engine crashes with a runtime error trying to convert an unknown variable to boolean, please go ahead and change

**Comment by kittaakos** [comment] 2018-01-30 18:20
I wanted to write a very simple test case to verify whether this is reproducible in node or not. Interestingly, it worked as expected when I ran the test module from VSCode (maybe it is due to `ts-node`) but was odd when I ran it with `npx run test @theia/core`. After some time, I have realized `jsdom` could cause this behavior. If I run the test from the terminal and print the `window` object, it is there. It throws an error when I debug into it from VSCode.

My questions are:
 - Is it really the `jsdom` dependency?
 - Does that mean we have a different environment for the tests and for "production"?
 - `Yes`
   - Is it good for us?
 - `No`
   - Then, it means we can close this ticket because `window` will be there any way under Node.js

If it is not the `jsdom` dependency, then what could be the problem with this simple test case:
```js
import { expect } from 'chai';
import { setRootLogger } from './logger';
import { MockLogger } from './test/mock-logger';

describe('logger', () => {

    it('setting the root logger should not throw an error when the window is not defined', () => {
        expect(() => setRootLogger(new MockLogger())).to.throw(ReferenceError, /window is not defined/);
    });

});
```

Cheers.

CC: @epatpol

**Comment by kittaakos** [comment] 2018-01-30 18:26
`jsdom` is a dev dependency. I assume we run the tests in a different environment.

**Comment by hexa00** [comment] 2018-01-30 19:29
@kittaakos `Then, it means we can close this ticket because window will be there any way under Node.js `

Is that a typo ? seems to me window should not be there on node.js

**Comment by epatpol** [comment] 2018-01-30 20:49
@kittaakos I'm not sure, it might be related to jsdom? I would have expected the tests to execute the same way on ts-node and on the terminal...

**Comment by epatpol** [comment] 2018-02-01 16:48
@AlexTugarev I'm not sure what's wrong here, I changed `keybinding.spec.ts` to use the new `cleanupJSDOM` but I think window is still defined even after `cleanupJSDOM()` is called, and that would cause @kittaakos test to execute differently in the terminal when running all the tests than when running *only* his test in vscode (because `keybinding.spec.ts` called jsdom and defined window beforehand).

**Comment by AlexTugarev** [comment] 2018-02-01 16:53
@epatpol, is there an issue with `jsdom` leaving a `window` defined?

**Comment by AlexTugarev** [comment] 2018-02-01 16:56
If that's the case, we can extend `cleanupJSDOM` to do `global.window = undefined`.

**Comment by hexa00** [comment] 2018-02-01 16:57
@AlexTugarev isn't it that we need window to be unknown ? so event undefined would not do ?

**Comment by epatpol** [comment] 2018-02-01 16:58
I don't think there's an issue opened as I just discovered that, not sure how to fix it yet

**Comment by AlexTugarev** [comment] 2018-02-01 20:04
@hexa00 setting `global.window` to `undefine` or the primitive `void 0` in `cleanupJSDOM` works fine with `describe('logger', ...)` from above. 

the actual issue I see here is a bit more severe, which is when to call `cleanupJSDOM` at all. I've learned that `npx run test @theia/core` will execute the `after` hooks after all tests. so there is indeed no issue with running tests in vscode, as the specs are executed separately.

the motivation to initialize `jsdom` before imports modules was, to enable loading of certain modules (via transpiled `require('module')`) in the first place.

**Comment by AlexTugarev** [comment] 2018-02-01 20:16
@hexa00 setting `global.window` to `undefine` or the primitive `void 0` in `cleanupJSDOM` works fine with `describe('logger', ...)` from above. 

the actual issue I see here is a bit more severe, which is when to call `cleanupJSDOM` at all. I've learned that `npx run test @theia/core` will execute the `after` hooks after all tests. so there is indeed no issue with running tests in vscode, as the specs are executed separately.

the motivation to initialize `jsdom` before imports modules was, to enable loading of certain modules (via transpiled `require('module')`) in the first place. I think it was mostly about undefined globals like `window`, `navigator`, and lots of types. 

the other requirement is, that we need to enable `jsdom` per test, right?

I suggest, we change the `jsdom` helper to work like this:
```typescript
import { enableJSDOM, disableJSDOM } from './test/jsdom';

enableJSDOM();
// some modules cannot be loaded otherwise
import { ... } from "module/depends/on/window"
disableJSDOM();

describe('something like keybindings', () => {
    before(() => {
        enableJSDOM();
    });
    ...
    after(() => {
        disableJSDOM();
    });
})
```

**Comment by hexa00** [comment] 2018-02-02 20:17
@AlexTugarev you mean the test fails ? it should fail since !!window should throw if there is no window variable, if the test passes it means that the environment is not the same.

**Comment by epatpol** [comment] 2018-02-02 22:12
@AlexTugarev Yes indeed I think it's better if we can enable jsdom for specific tests only.

The fix you suggested seems good, I'm ready to test it if you're willing to make a PR for it.

**Comment by kittaakos** [comment] 2018-02-05 12:20
Depends on #1207.

**Closed** 2018-02-05 15:19 UTC
Labels: bug
