### ISSUE TITLE
[java] The command 'java.ignoreIncompleteClasspath' cannot be executed.

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#2765] opened 2018-09-04 09:16 UTC
![screen shot 2018-09-04 at 11 08 56](https://user-images.githubusercontent.com/914497/45022104-a7cf4700-b033-11e8-81be-465193059211.png)

if you try to ignore those messages, an error logged raised in `JavaClientContribution.showActionableMessage`. 

> command.ts:191 Uncaught (in promise) The command 'java.ignoreIncompleteClasspath' cannot be executed. There are no active handlers available for the command.

we need to find out, if Java contribution needs to register that handler manually.

**Comment by kittaakos** [comment] 2018-09-04 09:45
Duplicate of https://github.com/theia-ide/theia/issues/2323?

**Closed** 2018-09-04 09:49 UTC
Labels: bug, java
