### ISSUE TITLE
Tasks test failures on macOS

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#1011] opened 2017-12-19 22:37 UTC
on macOS 10.13.2
node 8.9.2, npm 5.5.1
yarn 1.3.2

```
lerna ERR! execute   10 passing (22s)
lerna ERR! execute   2 failing
lerna ERR! execute 
lerna ERR! execute   1) Task server / back-end getTasks(ctx) returns tasks according to created context:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute   2) Task server / back-end creating and killing a bunch of tasks works as expected:
lerna ERR! execute      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
lerna ERR! execute   
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/Users/mark/git/theia/node_modules/execa/index.js:236:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:188:7)
lerna ERR! execute  callback with error

```

**Comment by vince-fugnitto** [comment] 2018-11-22 02:04
closing since the issue is quite old and currently works on `macOS`

**Closed by vince-fugnitto** 2018-11-22 02:04 UTC
Labels: OS/Mac
