### ISSUE TITLE
[Question][enhancement]Git history view should have a toggle command

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2033] opened 2018-06-04 13:51 UTC
For the Git History view, should we have a Toggle command like we have for the other views: Outline, Files, Search, Git ?

**Comment by kittaakos** [comment] 2018-06-04 15:41
This belongs to here: https://github.com/theia-ide/theia/issues/1727#issuecomment-385516906

I would close this as a duplicate. Feel free reopening this if I have overlooked something. Thanks!

Duplicate of #1727.

**Closed by kittaakos** 2018-06-04 15:41 UTC
Labels: duplicate
