### ISSUE TITLE
Can't open search-in-workspace result on Windows

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#3271] opened 2018-10-24 18:31 UTC
Double clicking on a SIW result doesn't open the editor.  In the backend, it says:

    root ERROR Request getFileStat failed with error: UNKNOWN: unknown error, stat '\\Users\Baube\theia\packages\task\src\node\task-server.slow-spec.ts' Error: UNKNOWN: unknown error, stat '\\Users\Baube\theia\packages\task\src\node\task-server.slow-spec.ts'

**Comment by westbury** [comment] 2018-12-04 15:09
Yes, it looks like this is, yet again, a problem with the paths.

The call to getFileStat is getting a string of the form:
"file:///%5CUsers%5Cnigwes01%5Cmbed-workspace%5Cmbed-cloud-client-example%5Cmbed-os%5CTESTS%5Cmbed_drivers%5Cticker%5Cmain.cpp"

going back to the client, we are trying to open the following string as a URI:
`
/\Users\nigwes01\mbed-workspace\mbed-cloud-client-example\mbed-os\TESTS\mbed_drivers\ticker\main.cpp
`

This is caused by this line:

`
            fileUri = new URI(node.file).withScheme('file');
`
(line 427, doOpen, in search-in-workspace-result-tree-widget.tsx)

Putting this into a test case, I see c:\path\file.cpp is converted by the above line to file:///\path\file.cpp, hence the results above.

I am happy to put in a PR that fixes this.  However I strongly believe that paths should simply not exist on the browser side.

**Comment by westbury** [comment] 2018-12-05 11:10
Yes, it would definitely help if the backend returned URIs instead of paths and I have started to make this change.  I have just noticed also issue https://github.com/theia-ide/theia/issues/1591 and I think the fix for this issue will have to also fix that issue.

**Comment by westbury** [comment] 2018-12-05 14:34
I have pushed the fix to https://github.com/westbury/theia/tree/GH-3271.  I need to some some more testing, and specifically I need to test on Linux or  OS/X.

This also fixes https://github.com/theia-ide/theia/issues/1591 and https://github.com/theia-ide/theia/issues/2731

**Comment by simark** [comment] 2018-12-05 15:39
> I have pushed the fix to https://github.com/westbury/theia/tree/GH-3271. I need to some some more testing, and specifically I need to test on Linux or OS/X.

Everything looks fine on Linux.

**Comment by westbury** [comment] 2018-12-05 16:56
Thanks, simark.  It was really helpful to know it tests ok on Linux as I would not have been able to check that for a while.  I have submitted the PR.

**Comment by westbury** [comment] 2018-12-06 20:11
This PR also fixes https://github.com/theia-ide/theia/issues/3772.

**Comment by elaihau** [comment] 2018-12-20 19:59
close this one as https://github.com/theia-ide/theia/pull/3749 was merged

**Closed by elaihau** 2018-12-20 19:59 UTC
Labels: OS/Windows, search in workspace
