### ISSUE TITLE
[electron] `Unhandled method validateKeyCode` error in a bundled electron application

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#5093] opened 2019-05-08 07:17 UTC
```
messages.js:46 Uncaught (in promise) Error: Unhandled method validateKeyCode
    at Proxy.<anonymous> (proxy-factory.ts:232)
    at KeyboardLayoutService../node_modules/@theia/core/lib/browser/keyboard/keyboard-layout-service.js.KeyboardLayoutService.validateKeyCode (keyboard-layout-service.ts:112)
    at KeybindingRegistry../node_modules/@theia/core/lib/browser/keybinding.js.KeybindingRegistry.run (keybinding.ts:614)
    at HTMLDocument.<anonymous> (frontend-application.ts:171)
ResponseError @ messages.js:46
handleResponse @ main.js:430
processMessageQueue @ main.js:258
(anonymous) @ main.js:242
runCallback @ timers.js:694
tryOnImmediate @ timers.js:665
processImmediate @ timers.js:647
```

I cannot share the effective `package.json` as is, once I managed to strip down the context, I'll update this PR with a reproducible configuration.

A few things before I start investigating the problem:
 -  I think we should not store the JSON files in the `src` folder: `@theia/core/src/common/keyboard/layouts`. For instance, for the TextMate grammars we use `data`, cannot we do the same?
 - [minor]: As a convention, we use `electron-node` and not `electron-main` for the electron specific Theia backend bindings: `@theia/core/src/electron-main/keyboard`. See the Git Theia extension.

**Comment by spoenemann** [comment] 2019-05-08 07:42
The problem is reproducible in `@theia/example-electron`.

**Comment by spoenemann** [comment] 2019-05-08 08:21
I need to wait until #5088 is merged to avoid merge conflicts.

**Closed** 2019-05-08 10:35 UTC
Labels: electron, keybindings
