### ISSUE TITLE
Trouble building following theia-ide.org instructions

### ISSUE THREAD

**Issue by abalter** [theia-ide/theia#5564] opened 2019-06-22 21:22 UTC
I can reproducibly create a clean Ubuntu install, install nodejs, npm, and yarn, and then have the simple build process [here](https://www.theia-ide.org/doc/composing_applications) fail with gyp errors.

I know there are more experienced programmers out there who obviously get things to work. But I'm also pretty sure I'm not the only person who runs into these problems and wants to give up.

The whole gyp error thing in Node is a huge problem, especially with gyp stuck on Python 2. There isn't anything you can do about that.

But I would really appreciate if the folks who have the know-how and authority to test their build system more extensively so that os mortal programmers can actually use Theia.

This is what I mean:

1. Install Ubuntu
1. Install nodejs, npm, yarn.
1. `mkdir ~/theia`
1. `cd ~/theia`
1. `vi package.json` and paste in the code below which I got from [here](https://www.theia-ide.org/doc/Composing_Applications.html)
1. `yarn
1. Get no errors
1. `yarn theia build`
1. Get no errors
1. `yarn theia start`

If you can get that to work consistently, then I'm happy to crawl back into my hole of ignorance.

__package.json__
```
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```

**Comment by vince-fugnitto** [comment] 2019-06-22 21:44
The prerequisites listed in the link you provided look outdated, so we will definitely need to update the documentation. Can you retry with the following [prerequisites](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites), and let us know if it helps?
There you will also see some helpful Linux troubleshooting dependencies which may help solve your issues. 

Also, it might be worthwhile to send the error messages you're getting so we can address them more easily.

**Comment by marechal-p** [comment] 2019-06-22 21:55
Maybe add `@theia/core: next` to your dependencies. Clean everything before rebuilding.

`node-gyp` depending on Python 2 shouldn't be an issue.

Please follow these instructions for your build environment setup:
https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites

You can also look at the Dockerfiles used in https://github.com/theia-ide/theia-apps to get ideas on how what to include in your `package.json` and what to install on your system.

**Comment by marechal-p** [comment] 2019-06-22 21:57
Please not that https://www.theia-ide.org/doc/composing_applications is slightly outdated (I see mention of node 8 when we now develop against 10).

Documentation is a standing issue indeed.

**Comment by abalter** [comment] 2019-06-22 22:54
I really don't want to be a jerk, but having such a fragile build system seems like the kind of thing that is not optimal for drawing in a larger community. Node is great. But the node build systems are not quite there yet.

**Comment by marechal-p** [comment] 2019-06-22 22:57
So what, re-implementing everything in C++ will make the building easier?

It is not fragile, there are requirements for the build to succeed. It is not Theia specific.

Documentation could be improved, this might be one of the reason for your troubles.

**Comment by abalter** [comment] 2019-06-22 22:57
@marechal-p --- indeed, the "prerequisites" link does seem to be updated. Thankyou.

**Comment by abalter** [comment] 2019-06-22 23:02
@marechal-p Noooo please not C++ <screaming>. I've run into problems with many node-based applications I try to install with npm and yarn. It's not Theia at all. I had a hell of a time getting through an introductory electron tutorial just because of node-gyp errors. I don't know the answer. And, I may be the only person out there who has problems. But if I'm not, then I'm probably not the only person who feels like giving up because I can't get past build system errors. FWIW, I have had more problems with npm and node than with `make && make install`. Again, not Theia specifically.

**Comment by marechal-p** [comment] 2019-06-22 23:07
Most `node-gyp` errors Theia related happen because of `native-keymap` that depends on OS-dependent libraries (as mentioned in the prerequisite documentation). If you are missing the libraries, then it may fail with what looks like an obscure message, but if you look through it the reason is often stated.

That's it. You would have the same issues with a `make && make install`-like project: if you are missing some packages, the build will fail.

Hopefully the resources linked in this issue will help you troubleshoot your issue.

**Comment by vince-fugnitto** [comment] 2019-07-03 19:04
Closing as it's a duplicate of #5184

**Closed by vince-fugnitto** 2019-07-03 19:04 UTC
Labels: question
