### ISSUE TITLE
Moved or renamed files are not saved anymore 

### ISSUE THREAD

**Issue by gorkem** [theia-ide/theia#1741] opened 2018-04-19 12:48 UTC
If a file is open on the editor and moved or renamed while it is open it can not be saved anymore. There is not also any indication that file can not be saved.

**Comment by AlexTugarev** [comment] 2018-04-19 12:52
This looks like a dupe of #230. Please reopen, if there is more to this.

**Closed by AlexTugarev** 2018-04-19 12:52 UTC
Labels: bug
