### ISSUE TITLE
[status-bar] Layout issues for the notifications in the status bar

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#5995] opened 2019-08-20 17:35 UTC
This is for a downstream project with `0.10.0-next.d059f9ed`.

Theia:
![Screen Shot 2019-08-20 at 13 32 25](https://user-images.githubusercontent.com/1405703/63369966-2b6e6a80-c34f-11e9-81e3-e2db354393fb.jpg)
![Screen Shot 2019-08-20 at 13 32 38](https://user-images.githubusercontent.com/1405703/63369967-2b6e6a80-c34f-11e9-95c8-c6c38bcbbae3.jpg)

VS Code:
![Screen Shot 2019-08-20 at 13 34 29](https://user-images.githubusercontent.com/1405703/63370022-47720c00-c34f-11e9-9f63-f4755e4ca473.jpg)

**Comment by AlexTugarev** [comment] 2019-08-21 09:42
@kittaakos, please help me to reproduce it. I tried with `0.10.0-next.f46ebf4e` in a Theia app, but it looks good.

![Screen Shot 2019-08-21 at 10 33 39](https://user-images.githubusercontent.com/914497/63416557-e6eed780-c3ff-11e9-96e7-a2d3dc58215e.png)

I can't find anything I can adjust in the config of this status bar item, so basically don't understand what went wrong there.

**Comment by kittaakos** [comment] 2019-08-21 13:09
> please help me to reproduce it

Sure, I will try to provide some hints. Bear with me.

**Comment by AlexTugarev** [comment] 2019-08-21 13:11
Thanks @kittaakos!

**Comment by kittaakos** [comment] 2019-08-21 23:46
It seems to be unrelated to the notification. I was just playing with https://github.com/TypeFox/theia-xtext-sprotty-example, and this is what I see on my status bar. I still do not know how to reproduce it.

![Screen Shot 2019-08-21 at 19 45 30](https://user-images.githubusercontent.com/1405703/63475800-64403980-c44c-11e9-815b-4ce387aa1eab.jpg)

**Comment by AlexTugarev** [comment] 2019-08-22 07:03
Thanks @kittaakos for the update. I'll quickly check if there is something special about the app's extension, and how this can happen at all.

**Comment by AlexTugarev** [comment] 2019-08-22 07:40
Nice catch! First I couldn't reproduce it (after going through the painful build & upgrade procedure,) but then trying out with different browsers I spotted this issue in Safari.

@kittaakos which browser is it for you?

![Screen Shot 2019-08-22 at 09 37 21](https://user-images.githubusercontent.com/914497/63495566-78258300-c4c0-11e9-9617-cb977d0f7553.png)

**Comment by AlexTugarev** [comment] 2019-08-22 09:12
@kittaakos, I found the 🐛 

this global `svg` style breaks status bar items and maybe more:

![Screen Shot 2019-08-22 at 11 04 04](https://user-images.githubusercontent.com/914497/63502260-7b733b80-c4cd-11e9-80a5-04b4c05c8547.png)

this is specific to the `theia-xtext-sprotty-example` which loads Sprotty style from here:
https://github.com/eclipse/sprotty-theia/blob/master/css/theia-sprotty.css

I'll file an issue for Sprotty.

**Comment by AlexTugarev** [comment] 2019-08-22 09:19
@kittaakos as this turns out to be an issue for Sprotty, can we close this?

**Closed** 2019-08-22 16:07 UTC
Labels: bug, statusbar, ui/ux
