### ISSUE TITLE
[plug-in] window.onDidChangeActiveTextEditor is not fired

### ISSUE THREAD

**Issue by vitaliy-guliy** [theia-ide/theia#4218] opened 2019-02-01 08:38 UTC
Sometimes when restoring the Theia layout after restoring opened files the theia.window.onDidChangeActiveTextEditor occasionally is not sent.
Plugin cannot handle active text editor properly.

**Comment by mmorhun** [comment] 2019-03-04 10:30
Cannot reproduce the described problem.
But during testing found that there is some focus related differences with VSCode: Theia triggers a new `onDidChangeActiveTextEditor` event when focus was taken and then returned back.

**Comment by mmorhun** [comment] 2019-03-11 08:04
Also VSCode fires the `onDidChangeActiveTextEditor` with undefined after an editor tab closing.

**Comment by mmorhun** [comment] 2019-03-11 12:40
Mentioned above incompatibilities are fixed in the PR above.

**Closed** 2019-03-11 12:39 UTC
Labels: Team: Che-IDE2, bug, plug-in system, vscode
