### ISSUE TITLE
Frontend fetches file from promisejs.org

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1314] opened 2018-02-19 21:21 UTC
I noticed that the example application fetches a file from promisejs.org.  I think that the applications should be self contained, since for various reasons we may not want or be able to fetch executables from the internet.

```
$ ag promisejs
dev-packages/application-package/src/generator/frontend-generator.ts
39:  <script type="text/javascript" src="https://www.promisejs.org/polyfills/promise-6.1.0.js" charset="utf-8"></script>`;

examples/browser/src-gen/frontend/index.html
6:  <script type="text/javascript" src="https://www.promisejs.org/polyfills/promise-6.1.0.js" charset="utf-8"></script>

examples/electron/src-gen/frontend/index.html
6:  <script type="text/javascript" src="https://www.promisejs.org/polyfills/promise-6.1.0.js" charset="utf-8"></script>
```

**Comment by kittaakos** [comment] 2018-02-20 07:12
Duplicate of #1290.

**Closed by kittaakos** 2018-02-20 07:12 UTC
Labels: duplicate

**Comment by kittaakos** [comment] 2018-02-20 07:13
@simark, please reopen this, if I have overlooked something, and this ticket is not a duplicate.
