### ISSUE TITLE
Problems related to LSP/Monaco integration

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#95] opened 2017-05-10 18:24 UTC
I have looked a bit at the LSP/Monaco integration. Here are my observations so far. I tested with the Java and C/C++ servers.

- Semantic Syntax Coloring: This was mentioned before but AFAIK this is not in the protocol. Is this really meant to be added at this moment? Perhaps via a protocol extension connecting to a different server? If so, how can I test?
- Code Completion: I see duplicated entries for Java. I think this could be a server problem? Seems to be fine for C/C++ (Clangd).
- Find References: Looks good!
- Go To Declaration: Doesn't seem to select the full range correctly, the cursor is placed at the beginning of the range. Is this a Monaco bug/by-design-behavior?
- Formatting: Looks good!
- Mark Occurrences: Looks good!
- Hover Information: Looks good!
- Quick Fixes: Does not seem to work? For Java and C/C++ (Clangd) at least. I tried to do "Quick Fix" from the command palette when my cursor at the location where there should be a code action. I also tried the "CMD+." shortcut displayed in the command palette.
- Signature Information: I'm not sure how to trigger it. Is there a way right now?
- Code lens: Seems to display "references" twice for Java?

**Comment by akosyakov** [comment] 2017-05-16 11:15
- [ ] duplicate providers: code lens, content assist, because java language is registered twice
- [ ] a selection is not revealed or revealed bogusly for go to declaration/reference
- [ ] quick fixes does not work

**Comment by akosyakov** [comment] 2017-05-16 11:48
> Go To Declaration: Doesn't seem to select the full range correctly, the cursor is placed at the beginning of the range. Is this a Monaco bug/by-design-behavior?

It's by design behavior.

**Comment by akosyakov** [comment] 2017-05-16 12:44
I've filed an issue for bogus hover ranges: https://github.com/Microsoft/vscode/issues/26747

**Comment by svenefftinge** [comment] 2017-08-16 08:55
The outstanding bug has been fixed by the vs code team.

**Closed by svenefftinge** 2017-08-16 08:55 UTC

**Comment by MarkZ3** [comment] 2017-08-24 14:09
@svenefftinge Do you know if the "quick fixes" work now? I haven't had the chance to test them.

**Comment by svenefftinge** [comment] 2017-08-24 14:53
Yes, I added that while working on yangster.
https://github.com/theia-ide/theia/pull/327

**Comment by MarkZ3** [comment] 2017-08-24 15:55
Thanks!
