### ISSUE TITLE
[git] view not wide enough to accommodate longer repo names

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#722] opened 2017-10-24 10:49 UTC
In the git view, on the first line, there's a combo box that contains the git repositories, detected in the current workspace. Then to the right there are the commit button, refresh button and "more..." menu. When one of the repo names contained in the combo box is a bit longer, the combo is made the same width as the view, hiding the buttons. 

Maybe the view width should be the width of the combo + enough space for the buttons?

![peek 2017-10-24 06-48](https://user-images.githubusercontent.com/25749063/31939109-67d9a4be-b887-11e7-979b-2485a3ead863.gif)

**Comment by lmcbout** [comment] 2017-10-24 11:04
I agree the text box for the git repo should be big enough. Although, if the repo name is very long, where do we stop to enlarge the window. I suggest to have a minimal with to show something  ~ 20 chars + size of the buttons for the view minimal width. If the name is exceeding this length, then the user should be able to hover the text box and we display the name of the branch in a tool-tip dialog. When the text is longer than 20 chars, then we display the last 17 chars + "..." to indicate the name is longer.

**Comment by kittaakos** [comment] 2017-10-24 11:26
Duplicate of #640.

**Closed by kittaakos** 2017-10-24 11:26 UTC
