### ISSUE TITLE
Search box in Explorer freeze after leaving the search area. 

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#5513] opened 2019-06-18 15:13 UTC
### Description

After editing the search box, click on the editor section, then try to modify the search pattern, It does not accept any characters until you select a file in the file explorer, then the search box goes away and you can initiate a new search after. May be a focus out event missing for the search box !

### Reproduction Steps
![SearchFreeze](https://user-images.githubusercontent.com/419051/59696198-8e118180-91b9-11e9-94c0-0a6684571db8.gif)

**OS and Theia version:**
Theia :    0.7.0
Ubuntu:  16:04

**Comment by kittaakos** [comment] 2019-06-24 15:09
> May be a focus out event missing for the search box !

It was by design; the search box does not accept focus. You can continue the filtering by setting the focus back to the `Explorer`.

![screencast 2019-06-24 17-04-57](https://user-images.githubusercontent.com/1405703/60030101-ad6d4a80-96a2-11e9-8b8c-632612012c6c.gif)

By the way, it is the "same" in VS Code; you cannot edit the search box.

**Comment by vince-fugnitto** [comment] 2019-07-05 12:51
Closed in #5563

**Closed by vince-fugnitto** 2019-07-05 12:51 UTC
Labels: bug, help wanted, tree
