### ISSUE TITLE
@theia/git install error in Node v12.2.0

### ISSUE THREAD

**Issue by Lakkanna** [theia-ide/theia#5689] opened 2019-07-11 06:13 UTC
### Description
 Getting issues while installing **@theia/git**, node verison 12.2.0

### Reproduction Steps

![Screen Shot 2019-07-11 at 11 27 09 AM](https://user-images.githubusercontent.com/32791713/61025956-c2025000-a3cf-11e9-8a27-0ec4f3c17fde.png)

**OS and Theia version:**
 MacOS - High Sierrra
Theia: 0.8.0

**Diagnostics:** 

![Screen Shot 2019-07-11 at 11 41 10 AM](https://user-images.githubusercontent.com/32791713/61026400-d5fa8180-a3d0-11e9-81f7-d35ebed7744b.png)

**Comment by kittaakos** [comment] 2019-07-11 06:24
Thanks for logging it, @Lakkanna!
This is a duplicate of #5117.
Please reference the required Node.js version in the [prerequisites](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites).

**Closed by kittaakos** 2019-07-11 06:24 UTC
